In [2]:
import pandas as pd
import numpy as np

In [4]:
# Get the data from Sutdent.csv into Datafram
df=pd.read_csv("D:\\Akash\\Python\\KVR-PYTHON-PART-1\\PANDAS\\NOTES\\Student.csv")
print("="*50)
print("{}".format(df))
print("="*50)

==================================================
    htno     name  telugu  english  hindi  maths  science  social
0    100   Ramesh      50       60     66     98       66      55
1    101   Rajesh      45       67     34     67       66      78
2    102   Rossum      56       88     56     99       44      77
3    103     Raji      56       78     34     56       88      55
4    104   Kalyan      51       63     62     93       67      51
5    105  Karthik      48       62     39     68       65      88
6    106   Kambli      53       81     59     92       48      73
7    107  Praveen      46       88     74     86       78      45
8    108   Ganesh      53       62     76     88       76      35
9    109     Nags      55       77     44     77       86      58
10   110    Biswa      66       48     86     95       48      47
11   111   Ritchi      66       68     64     76       98      75
12   104   Kalyan      51       63     62     93       67      51
13   112  shareef      50       63     99     90       76      67
14   113     sonu      60       89     98     87       77      68
15   114   Rajesh      45       67     77     55       66      46
16   115   Rakesh      67       78     88     78       67      49
==================================================

In [5]:
  # Obtain first five Record / ROw from datafreame we use DataFrameobj.head()
print("First Five Records or Rows")
df.head()

First Five Records or Rows

   htno    name  telugu  english  hindi  maths  science  social
0   100  Ramesh      50       60     66     98       66      55
1   101  Rajesh      45       67     34     67       66      78
2   102  Rossum      56       88     56     99       44      77
3   103    Raji      56       78     34     56       88      55
4   104  Kalyan      51       63     62     93       67      51

In [9]:
  # Obtain first five Record / ROw from datafreame we use DataFrameobj.head()
# Here are creating sub DataFrame by containg First Five Row/Records
print("First Five Records or Rows")
firstFive=df.head()  #Here First Five is object of DataFrame and Considered as sub DataFrame
print(firstFive,"\n",type(firstFive))

First Five Records or Rows
   htno    name  telugu  english  hindi  maths  science  social
0   100  Ramesh      50       60     66     98       66      55
1   101  Rajesh      45       67     34     67       66      78
2   102  Rossum      56       88     56     99       44      77
3   103    Raji      56       78     34     56       88      55
4   104  Kalyan      51       63     62     93       67      51
 <class 'pandas.core.frame.DataFrame'>

In [10]:
# Obtaing First 3 Record / Row from datafreame we use DataFrameobj.head(no. of row) 
print("First Three Records or Rows")
df.head(3)

First Three Records or Rows

   htno    name  telugu  english  hindi  maths  science  social
0   100  Ramesh      50       60     66     98       66      55
1   101  Rajesh      45       67     34     67       66      78
2   102  Rossum      56       88     56     99       44      77

In [11]:
print("First three Records or Rows")
firstthree=df.head(3)  #Here First 3 is object of DataFrame and Considered as sub DataFrame
print(firstthree,"\n",type(firstthree))

First three Records or Rows
   htno    name  telugu  english  hindi  maths  science  social
0   100  Ramesh      50       60     66     98       66      55
1   101  Rajesh      45       67     34     67       66      78
2   102  Rossum      56       88     56     99       44      77
 <class 'pandas.core.frame.DataFrame'>

In [14]:
# Obtain last five Record / ROw from datafreame we use DataFrameobj.tail()
print("Last Five Records or Rows")
df.tail()

Last Five Records or Rows

    htno     name  telugu  english  hindi  maths  science  social
12   104   Kalyan      51       63     62     93       67      51
13   112  shareef      50       63     99     90       76      67
14   113     sonu      60       89     98     87       77      68
15   114   Rajesh      45       67     77     55       66      46
16   115   Rakesh      67       78     88     78       67      49

In [16]:
  # Obtain Last five Record / ROw from datafreame we use DataFrameobj.tail()
# Here are creating sub DataFrame by containg last Five Row/Records
print("Last Five Records or Rows")
lastFive=df.tail()  #Here lat Five is object of DataFrame and Considered as sub DataFrame
print(lastFive,"\n",type(lastFive))

Last Five Records or Rows
    htno     name  telugu  english  hindi  maths  science  social
12   104   Kalyan      51       63     62     93       67      51
13   112  shareef      50       63     99     90       76      67
14   113     sonu      60       89     98     87       77      68
15   114   Rajesh      45       67     77     55       66      46
16   115   Rakesh      67       78     88     78       67      49
 <class 'pandas.core.frame.DataFrame'>

In [18]:
# Obtain thd Statical Information on DataFrame Data
print("="*50)
print("{}".format(df))
print("="*50)
print("Stastcal Information o DataFrame Object Data")
df.describe()

==================================================
    htno     name  telugu  english  hindi  maths  science  social
0    100   Ramesh      50       60     66     98       66      55
1    101   Rajesh      45       67     34     67       66      78
2    102   Rossum      56       88     56     99       44      77
3    103     Raji      56       78     34     56       88      55
4    104   Kalyan      51       63     62     93       67      51
5    105  Karthik      48       62     39     68       65      88
6    106   Kambli      53       81     59     92       48      73
7    107  Praveen      46       88     74     86       78      45
8    108   Ganesh      53       62     76     88       76      35
9    109     Nags      55       77     44     77       86      58
10   110    Biswa      66       48     86     95       48      47
11   111   Ritchi      66       68     64     76       98      75
12   104   Kalyan      51       63     62     93       67      51
13   112  shareef      50       63     99     90       76      67
14   113     sonu      60       89     98     87       77      68
15   114   Rajesh      45       67     77     55       66      46
16   115   Rakesh      67       78     88     78       67      49
==================================================
Stastcal Information o DataFrame Object Data

,htno,telugu,english,hindi,maths,science,social
count,17.000000,17.000000,17.000000,17.000000,17.000000,17.000000,17.000000
mean,107.294118,54.000000,70.705882,65.764706,82.235294,69.588235,59.882353
std,4.687279,7.141428,11.671358,20.504662,13.917298,14.339887,14.696438
min,100.000000,45.000000,48.000000,34.000000,55.000000,44.000000,35.000000
25%,104.000000,50.000000,63.000000,56.000000,76.000000,66.000000,49.000000
50%,107.000000,53.000000,67.000000,64.000000,87.000000,67.000000,55.000000
75%,111.000000,56.000000,78.000000,77.000000,93.000000,77.000000,73.000000
max,115.000000,67.000000,89.000000,99.000000,99.000000,98.000000,88.000000

In [24]:
# Obtain the Shape of DataFrame Object
print("="*50)
print("{}".format(df))
print("="*50)
print("Shape of DataFrame Object Data")
print(df.shape)
print("No. Of column =",df.shape[0])
print("No. of Rows =",df.shape[1])

==================================================
    htno     name  telugu  english  hindi  maths  science  social
0    100   Ramesh      50       60     66     98       66      55
1    101   Rajesh      45       67     34     67       66      78
2    102   Rossum      56       88     56     99       44      77
3    103     Raji      56       78     34     56       88      55
4    104   Kalyan      51       63     62     93       67      51
5    105  Karthik      48       62     39     68       65      88
6    106   Kambli      53       81     59     92       48      73
7    107  Praveen      46       88     74     86       78      45
8    108   Ganesh      53       62     76     88       76      35
9    109     Nags      55       77     44     77       86      58
10   110    Biswa      66       48     86     95       48      47
11   111   Ritchi      66       68     64     76       98      75
12   104   Kalyan      51       63     62     93       67      51
13   112  shareef      50       63     99     90       76      67
14   113     sonu      60       89     98     87       77      68
15   114   Rajesh      45       67     77     55       66      46
16   115   Rakesh      67       78     88     78       67      49
==================================================
Shape of DataFrame Object Data
(17, 8)
No. Of column = 17
No. of Rows = 8

In [25]:
df.columns

Index(['htno', 'name', 'telugu', 'english', 'hindi', 'maths', 'science',
       'social'],
      dtype='object')

In [26]:
df.index

RangeIndex(start=0, stop=17, step=1)

In [29]:
# On DataFrame Object, we can Also perform Slicing operations for getting desired row
df=pd.read_csv("D:\\Akash\\Python\\KVR-PYTHON-PART-1\\PANDAS\\NOTES\\Student.csv")
print("="*50)
print("{}".format(df))
print("="*50)

==================================================
    htno     name  telugu  english  hindi  maths  science  social
0    100   Ramesh      50       60     66     98       66      55
1    101   Rajesh      45       67     34     67       66      78
2    102   Rossum      56       88     56     99       44      77
3    103     Raji      56       78     34     56       88      55
4    104   Kalyan      51       63     62     93       67      51
5    105  Karthik      48       62     39     68       65      88
6    106   Kambli      53       81     59     92       48      73
7    107  Praveen      46       88     74     86       78      45
8    108   Ganesh      53       62     76     88       76      35
9    109     Nags      55       77     44     77       86      58
10   110    Biswa      66       48     86     95       48      47
11   111   Ritchi      66       68     64     76       98      75
12   104   Kalyan      51       63     62     93       67      51
13   112  shareef      50       63     99     90       76      67
14   113     sonu      60       89     98     87       77      68
15   114   Rajesh      45       67     77     55       66      46
16   115   Rakesh      67       78     88     78       67      49
==================================================

In [30]:
df[4:10]

   htno     name  telugu  english  hindi  maths  science  social
4   104   Kalyan      51       63     62     93       67      51
5   105  Karthik      48       62     39     68       65      88
6   106   Kambli      53       81     59     92       48      73
7   107  Praveen      46       88     74     86       78      45
8   108   Ganesh      53       62     76     88       76      35
9   109     Nags      55       77     44     77       86      58

In [32]:
df1=df[4:10]
print("Sub Data Frame from Main Dataframe Object")
print(df1)

Sub Data Frame from Main Dataframe Object
   htno     name  telugu  english  hindi  maths  science  social
4   104   Kalyan      51       63     62     93       67      51
5   105  Karthik      48       62     39     68       65      88
6   106   Kambli      53       81     59     92       48      73
7   107  Praveen      46       88     74     86       78      45
8   108   Ganesh      53       62     76     88       76      35
9   109     Nags      55       77     44     77       86      58

In [33]:
df1=df[10:4]
print("Sub Data Frame from Main Dataframe Object")
print(df1)

Sub Data Frame from Main Dataframe Object
Empty DataFrame
Columns: [htno, name, telugu, english, hindi, maths, science, social]
Index: []

In [34]:
df1=df[10:4:-1]
print("Sub Data Frame from Main Dataframe Object")
print(df1)

Sub Data Frame from Main Dataframe Object
    htno     name  telugu  english  hindi  maths  science  social
10   110    Biswa      66       48     86     95       48      47
9    109     Nags      55       77     44     77       86      58
8    108   Ganesh      53       62     76     88       76      35
7    107  Praveen      46       88     74     86       78      45
6    106   Kambli      53       81     59     92       48      73
5    105  Karthik      48       62     39     68       65      88

In [36]:
print(df[::-1])

    htno     name  telugu  english  hindi  maths  science  social
16   115   Rakesh      67       78     88     78       67      49
15   114   Rajesh      45       67     77     55       66      46
14   113     sonu      60       89     98     87       77      68
13   112  shareef      50       63     99     90       76      67
12   104   Kalyan      51       63     62     93       67      51
11   111   Ritchi      66       68     64     76       98      75
10   110    Biswa      66       48     86     95       48      47
9    109     Nags      55       77     44     77       86      58
8    108   Ganesh      53       62     76     88       76      35
7    107  Praveen      46       88     74     86       78      45
6    106   Kambli      53       81     59     92       48      73
5    105  Karthik      48       62     39     68       65      88
4    104   Kalyan      51       63     62     93       67      51
3    103     Raji      56       78     34     56       88      55
2    102   Rossum      56       88     56     99       44      77
1    101   Rajesh      45       67     34     67       66      78
0    100   Ramesh      50       60     66     98       66      55

In [37]:
print(df[::-2])

    htno    name  telugu  english  hindi  maths  science  social
16   115  Rakesh      67       78     88     78       67      49
14   113    sonu      60       89     98     87       77      68
12   104  Kalyan      51       63     62     93       67      51
10   110   Biswa      66       48     86     95       48      47
8    108  Ganesh      53       62     76     88       76      35
6    106  Kambli      53       81     59     92       48      73
4    104  Kalyan      51       63     62     93       67      51
2    102  Rossum      56       88     56     99       44      77
0    100  Ramesh      50       60     66     98       66      55

In [39]:
# Center data find
df[len(df)//2:(len(df)//2)+1]

   htno    name  telugu  english  hindi  maths  science  social
8   108  Ganesh      53       62     76     88       76      35

In [40]:
# Extract the Data From DataFram Based on Column

In [41]:
df=pd.read_csv("D:\\Akash\\Python\\KVR-PYTHON-PART-1\\PANDAS\\NOTES\\Student.csv")
print("="*50)
print("{}".format(df))
print("="*50)

==================================================
    htno     name  telugu  english  hindi  maths  science  social
0    100   Ramesh      50       60     66     98       66      55
1    101   Rajesh      45       67     34     67       66      78
2    102   Rossum      56       88     56     99       44      77
3    103     Raji      56       78     34     56       88      55
4    104   Kalyan      51       63     62     93       67      51
5    105  Karthik      48       62     39     68       65      88
6    106   Kambli      53       81     59     92       48      73
7    107  Praveen      46       88     74     86       78      45
8    108   Ganesh      53       62     76     88       76      35
9    109     Nags      55       77     44     77       86      58
10   110    Biswa      66       48     86     95       48      47
11   111   Ritchi      66       68     64     76       98      75
12   104   Kalyan      51       63     62     93       67      51
13   112  shareef      50       63     99     90       76      67
14   113     sonu      60       89     98     87       77      68
15   114   Rajesh      45       67     77     55       66      46
16   115   Rakesh      67       78     88     78       67      49
==================================================

In [43]:
# Get the Sanmes of Student
seriesobj=df["name"]
print(seriesobj,type(seriesobj))

0      Ramesh
1      Rajesh
2      Rossum
3        Raji
4      Kalyan
5     Karthik
6      Kambli
7     Praveen
8      Ganesh
9        Nags
10      Biswa
11     Ritchi
12     Kalyan
13    shareef
14       sonu
15     Rajesh
16     Rakesh
Name: name, dtype: object <class 'pandas.core.series.Series'>

In [44]:
# Get the Lanf of Student
seriesobj=df["hindi"]
print(seriesobj,type(seriesobj))

0     66
1     34
2     56
3     34
4     62
5     39
6     59
7     74
8     76
9     44
10    86
11    64
12    62
13    99
14    98
15    77
16    88
Name: hindi, dtype: int64 <class 'pandas.core.series.Series'>

In [45]:
# Get the names and lang of Student
df[["name","hindi"]]

       name  hindi
0    Ramesh     66
1    Rajesh     34
2    Rossum     56
3      Raji     34
4    Kalyan     62
5   Karthik     39
6    Kambli     59
7   Praveen     74
8    Ganesh     76
9      Nags     44
10    Biswa     86
11   Ritchi     64
12   Kalyan     62
13  shareef     99
14     sonu     98
15   Rajesh     77
16   Rakesh     88

In [46]:
df[["name","maths"]]

       name  maths
0    Ramesh     98
1    Rajesh     67
2    Rossum     99
3      Raji     56
4    Kalyan     93
5   Karthik     68
6    Kambli     92
7   Praveen     86
8    Ganesh     88
9      Nags     77
10    Biswa     95
11   Ritchi     76
12   Kalyan     93
13  shareef     90
14     sonu     87
15   Rajesh     55
16   Rakesh     78

In [47]:
seriesobj=df[["name","hindi"]]
print(seriesobj,type(seriesobj))

       name  hindi
0    Ramesh     66
1    Rajesh     34
2    Rossum     56
3      Raji     34
4    Kalyan     62
5   Karthik     39
6    Kambli     59
7   Praveen     74
8    Ganesh     76
9      Nags     44
10    Biswa     86
11   Ritchi     64
12   Kalyan     62
13  shareef     99
14     sonu     98
15   Rajesh     77
16   Rakesh     88 <class 'pandas.core.frame.DataFrame'>

In [48]:
# Perform Slicing Operation on DatFrame by Using Column Name
df[["name","hindi"]][7:10]

      name  hindi
7  Praveen     74
8   Ganesh     76
9     Nags     44

In [52]:
df[["name","hindi"]][::3]

      name  hindi
0   Ramesh     66
3     Raji     34
6   Kambli     59
9     Nags     44
12  Kalyan     62
15  Rajesh     77

In [50]:
df[["name","hindi"]][::3][::-1]

      name  hindi
15  Rajesh     77
12  Kalyan     62
9     Nags     44
6   Kambli     59
3     Raji     34
0   Ramesh     66

In [53]:
df[["name"]][5:9]

      name
5  Karthik
6   Kambli
7  Praveen
8   Ganesh

In [54]:
# Get th Data from DataFram by using iterrows{}
df=pd.read_csv("D:\\Akash\\Python\\KVR-PYTHON-PART-1\\PANDAS\\NOTES\\Student.csv")
print("="*50)
print("{}".format(df))
print("="*50)

==================================================
    htno     name  telugu  english  hindi  maths  science  social
0    100   Ramesh      50       60     66     98       66      55
1    101   Rajesh      45       67     34     67       66      78
2    102   Rossum      56       88     56     99       44      77
3    103     Raji      56       78     34     56       88      55
4    104   Kalyan      51       63     62     93       67      51
5    105  Karthik      48       62     39     68       65      88
6    106   Kambli      53       81     59     92       48      73
7    107  Praveen      46       88     74     86       78      45
8    108   Ganesh      53       62     76     88       76      35
9    109     Nags      55       77     44     77       86      58
10   110    Biswa      66       48     86     95       48      47
11   111   Ritchi      66       68     64     76       98      75
12   104   Kalyan      51       63     62     93       67      51
13   112  shareef      50       63     99     90       76      67
14   113     sonu      60       89     98     87       77      68
15   114   Rajesh      45       67     77     55       66      46
16   115   Rakesh      67       78     88     78       67      49
==================================================

In [55]:
for record in df.iterrows():
    print("="*50)
    print(record)

==================================================
(0, htno          100
name       Ramesh
telugu         50
english        60
hindi          66
maths          98
science        66
social         55
Name: 0, dtype: object)
==================================================
(1, htno          101
name       Rajesh
telugu         45
english        67
hindi          34
maths          67
science        66
social         78
Name: 1, dtype: object)
==================================================
(2, htno          102
name       Rossum
telugu         56
english        88
hindi          56
maths          99
science        44
social         77
Name: 2, dtype: object)
==================================================
(3, htno        103
name       Raji
telugu       56
english      78
hindi        34
maths        56
science      88
social       55
Name: 3, dtype: object)
==================================================
(4, htno          104
name       Kalyan
telugu         51
english        63
hindi          62
maths          93
science        67
social         51
Name: 4, dtype: object)
==================================================
(5, htno           105
name       Karthik
telugu          48
english         62
hindi           39
maths           68
science         65
social          88
Name: 5, dtype: object)
==================================================
(6, htno          106
name       Kambli
telugu         53
english        81
hindi          59
maths          92
science        48
social         73
Name: 6, dtype: object)
==================================================
(7, htno           107
name       Praveen
telugu          46
english         88
hindi           74
maths           86
science         78
social          45
Name: 7, dtype: object)
==================================================
(8, htno          108
name       Ganesh
telugu         53
english        62
hindi          76
maths          88
science        76
social         35
Name: 8, dtype: object)
==================================================
(9, htno        109
name       Nags
telugu       55
english      77
hindi        44
maths        77
science      86
social       58
Name: 9, dtype: object)
==================================================
(10, htno         110
name       Biswa
telugu        66
english       48
hindi         86
maths         95
science       48
social        47
Name: 10, dtype: object)
==================================================
(11, htno          111
name       Ritchi
telugu         66
english        68
hindi          64
maths          76
science        98
social         75
Name: 11, dtype: object)
==================================================
(12, htno          104
name       Kalyan
telugu         51
english        63
hindi          62
maths          93
science        67
social         51
Name: 12, dtype: object)
==================================================
(13, htno           112
name       shareef
telugu          50
english         63
hindi           99
maths           90
science         76
social          67
Name: 13, dtype: object)
==================================================
(14, htno        113
name       sonu
telugu       60
english      89
hindi        98
maths        87
science      77
social       68
Name: 14, dtype: object)
==================================================
(15, htno          114
name       Rajesh
telugu         45
english        67
hindi          77
maths          55
science        66
social         46
Name: 15, dtype: object)
==================================================
(16, htno          115
name       Rakesh
telugu         67
english        78
hindi          88
maths          78
science        67
social         49
Name: 16, dtype: object)