In [1]:
import pandas as pd
import numpy as np

In [2]:
# Get the data from Sutdent.csv into Datafram
df=pd.read_csv("D:\\Akash\\Python\\KVR-PYTHON-PART-1\\PANDAS\\NOTES\\peoples.csv")
print("="*50)
print("{}".format(df))
print("="*50)

==================================================
    CID      CNAME  STATE DSG
0   100      SUSMA     TS  SE
1   200   SAGATIKA     AP  SE
2   300      LAXMI     TS  TL
3   400     ROSSUM     AP  TL
4   500     NARESH  DELHI  PM
5   600      VINAY  DELHI   M
6   700  TEJASWANI     AP  SE
7   800     FAZINA     TS  PM
8   900    SANSKAR  DELHI  SE
9   750        KVR     AP  PM
10  650      RADHA   BANG  TL
11  550    MOUNIKA     AP  PM
12  350    SIRISHA     TS  HR
13  150    MADHVAI     AP  HR
14  450   JAYSHREE   BANG  HR
15  950     ANJALI     AP  HR
16  250      KOMAL     TS  TL
==================================================

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   CID     17 non-null     int64
 1   CNAME   17 non-null     object
 2   STATE   17 non-null     object
 3   DSG     17 non-null     object
dtypes: int64(1), object(3)
memory usage: 676.0+ bytes

In [7]:
# Syntax 1: DataFrameObject.loc[row_number]
# get 7th record
df.loc[7]

CID         800
CNAME    FAZINA
STATE        TS
DSG          PM
Name: 7, dtype: object

In [8]:
df.loc[3]

CID         400
CNAME    ROSSUM
STATE        AP
DSG          TL
Name: 3, dtype: object

In [9]:
df.loc[30]

KeyError: 30

In [10]:
# Syntax 2: DataFrameObject.loc[row_number,[Column_name]]
# get 7th record name
df.loc[7,["CNAME"]]

CNAME    FAZINA
Name: 7, dtype: object

In [14]:
# get 2th record name
df.loc[2,["CNAME"]]

CNAME    LAXMI
Name: 2, dtype: object

In [15]:
df.loc[2,["CNAME","EXP"]]

KeyError: "['EXP'] not in index"

In [ ]:
# Syntax 3: DataFrameObject.loc[RowBegainIndex:RowEndIndex:Step]
# get 3th to 7th record name
df.loc[3:7]

In [13]:
df.loc[::2]

    CID      CNAME  STATE DSG
0   100      SUSMA     TS  SE
2   300      LAXMI     TS  TL
4   500     NARESH  DELHI  PM
6   700  TEJASWANI     AP  SE
8   900    SANSKAR  DELHI  SE
10  650      RADHA   BANG  TL
12  350    SIRISHA     TS  HR
14  450   JAYSHREE   BANG  HR
16  250      KOMAL     TS  TL

In [12]:
# Syntax 4: DataFrameObject.loc[owBegainIndex:RowEndIndex:Step,[Column_name]]
# get 3rd to 7th record name
df.loc[3:7,["CNAME","EXP"]]

KeyError: "['EXP'] not in index"

In [ ]:
print(df)

In [18]:
# 
df.loc[4:6,"CNAME"::2]

       CNAME DSG
4     NARESH  PM
5      VINAY   M
6  TEJASWANI  SE

In [20]:
df.loc[2:6,"CNAME"::1]

       CNAME  STATE DSG
2      LAXMI     TS  TL
3     ROSSUM     AP  TL
4     NARESH  DELHI  PM
5      VINAY  DELHI   M
6  TEJASWANI     AP  SE

In [17]:
df.loc[2:6,"CNAME":]

       CNAME  STATE DSG
2      LAXMI     TS  TL
3     ROSSUM     AP  TL
4     NARESH  DELHI  PM
5      VINAY  DELHI   M
6  TEJASWANI     AP  SE

In [ ]:
df.loc[2:6,"CID":"EXP"]

In [ ]:
df.loc[2:6,::-1]

In [ ]:
for name in df["CNAME"]:
    print(name[0:2])