In [1]:
import pandas as pd

In [2]:
# Get Employee Data set into DataFrame
df=pd.read_csv("D:\\Akash\\Python\\KVR-PYTHON-PART-1\\PANDAS\\NOTES\\employee.csv")
print(df)

   ENO    NAME    SAL   COMM    COMPNAME
0  100  Rossum  34.56  10.00         PSF
1  200  Travis  22.23  15.00       Numpy
2  300  Kinney  45.67  26.34      Pandas
3  400  Hunter  12.45   5.60  Matplotlib
4  500  Dennis   3.40   1.20    BellLabs

In [4]:
# 
df["SAL"]>20.00

0     True
1     True
2     True
3    False
4    False
Name: SAL, dtype: bool

In [5]:
df[df["SAL"]>20.00]

   ENO    NAME    SAL   COMM COMPNAME
0  100  Rossum  34.56  10.00      PSF
1  200  Travis  22.23  15.00    Numpy
2  300  Kinney  45.67  26.34   Pandas

In [6]:
df[df["SAL"]<20.00]

   ENO    NAME    SAL  COMM    COMPNAME
3  400  Hunter  12.45   5.6  Matplotlib
4  500  Dennis   3.40   1.2    BellLabs

In [7]:
df[df["SAL"]>20.00]["NAME"]

0    Rossum
1    Travis
2    Kinney
Name: NAME, dtype: object

In [9]:
df[df["SAL"]>20.00][["NAME","SAL"]]

     NAME    SAL
0  Rossum  34.56
1  Travis  22.23
2  Kinney  45.67

In [16]:
print(df)
# Get those emp name sal wj=hose aaaasal b/w 10.00 and 15.00
(df["SAL"]>=10.00) & (df["SAL"]<=25.00)

   ENO    NAME    SAL   COMM    COMPNAME
0  100  Rossum  34.56  10.00         PSF
1  200  Travis  22.23  15.00       Numpy
2  300  Kinney  45.67  26.34      Pandas
3  400  Hunter  12.45   5.60  Matplotlib
4  500  Dennis   3.40   1.20    BellLabs

0    False
1     True
2    False
3     True
4    False
Name: SAL, dtype: bool

In [17]:
print(df)
# Get those emp name sal wj=hose aaaasal b/w 10.00 and 15.00
df[(df["SAL"]>=10.00) & (df["SAL"]<=25.00)]

   ENO    NAME    SAL   COMM    COMPNAME
0  100  Rossum  34.56  10.00         PSF
1  200  Travis  22.23  15.00       Numpy
2  300  Kinney  45.67  26.34      Pandas
3  400  Hunter  12.45   5.60  Matplotlib
4  500  Dennis   3.40   1.20    BellLabs

   ENO    NAME    SAL  COMM    COMPNAME
1  200  Travis  22.23  15.0       Numpy
3  400  Hunter  12.45   5.6  Matplotlib

In [19]:
print(df)
# Get those emp name sal wj=hose aaaasal b/w 10.00 and 15.00
df[(df["SAL"]>=10.00) & (df["SAL"]<=25.00)][["NAME","SAL"]]

   ENO    NAME    SAL   COMM    COMPNAME
0  100  Rossum  34.56  10.00         PSF
1  200  Travis  22.23  15.00       Numpy
2  300  Kinney  45.67  26.34      Pandas
3  400  Hunter  12.45   5.60  Matplotlib
4  500  Dennis   3.40   1.20    BellLabs

     NAME    SAL
1  Travis  22.23
3  Hunter  12.45

In [21]:
# Get the Name and Sal of The Employee who is working in "Numo]py"
df[df["COMPNAME"]=="Numpy"]

   ENO    NAME    SAL  COMM COMPNAME
1  200  Travis  22.23  15.0    Numpy

In [22]:
df["SAL"].sum()

np.float64(118.31000000000002)

In [23]:
df["SAL"].mean()

np.float64(23.662000000000003)

In [25]:
# Get the Name of employee who o=working in Numpy and Panda
df[(df["COMPNAME"]=="Numpy") | (df["COMPNAME"]=="Pandas")]

   ENO    NAME    SAL   COMM COMPNAME
1  200  Travis  22.23  15.00    Numpy
2  300  Kinney  45.67  26.34   Pandas

In [27]:
# Get the Name of employee who o=working in Numpy and Panda
df[(df["COMPNAME"]=="Numpy") | (df["COMPNAME"]=="Pandas")]["NAME"]

1    Travis
2    Kinney
Name: NAME, dtype: object

In [29]:
for cname in df["COMPNAME"]:
    if cname in["Numpy","Pandas"]:
        print(cname)

Numpy
Pandas

In [36]:
x=dict(df[["NAME","COMPNAME"]])
for na, ca in x.items():
    if (ca=="Numpy") or (ca=="Pandas"):
        print(ca,na)

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [38]:
# Get the Name of employee who o=working in Numpy and Panda
df.loc[(df["COMPNAME"]=="Numpy") | (df["COMPNAME"]=="Pandas")]

   ENO    NAME    SAL   COMM COMPNAME
1  200  Travis  22.23  15.00    Numpy
2  300  Kinney  45.67  26.34   Pandas

In [40]:
# Get the Name of employee who o=working in Numpy and Panda
df.loc[(df["COMPNAME"]=="Numpy") | (df["COMPNAME"]=="Pandas")]["NAME"]

1    Travis
2    Kinney
Name: NAME, dtype: object

In [42]:
# Get the Name of employee who o=working in Numpy and Panda
df.loc[(df["COMPNAME"]=="Numpy") | (df["COMPNAME"]=="Pandas"),["NAME"]]

     NAME
1  Travis
2  Kinney