In [1]:
import pandas as pd

In [3]:
# Get Employee Data set into DataFrame
df=pd.read_csv("D:\\Akash\\Python\\KVR-PYTHON-PART-1\\PANDAS\\NOTES\\peoples.csv")
print(df)

    CID      CNAME  STATE DSG
0   100      SUSMA     TS  SE
1   200   SAGATIKA     AP  SE
2   300      LAXMI     TS  TL
3   400     ROSSUM     AP  TL
4   500     NARESH  DELHI  PM
5   600      VINAY  DELHI   M
6   700  TEJASWANI     AP  SE
7   800     FAZINA     TS  PM
8   900    SANSKAR  DELHI  SE
9   750        KVR     AP  PM
10  650      RADHA   BANG  TL
11  550    MOUNIKA     AP  PM
12  350    SIRISHA     TS  HR
13  150    MADHVAI     AP  HR
14  450   JAYSHREE   BANG  HR
15  950     ANJALI     AP  HR
16  250      KOMAL     TS  TL

In [4]:
df.columns

Index(['CID', 'CNAME', 'STATE', 'DSG'], dtype='object')

In [5]:
df["STATE"]

0        TS
1        AP
2        TS
3        AP
4     DELHI
5     DELHI
6        AP
7        TS
8     DELHI
9        AP
10     BANG
11       AP
12       TS
13       AP
14     BANG
15       AP
16       TS
Name: STATE, dtype: object

In [8]:
df["STATE"]=="AP"

0     False
1      True
2     False
3      True
4     False
5     False
6      True
7     False
8     False
9      True
10    False
11     True
12    False
13     True
14    False
15     True
16    False
Name: STATE, dtype: bool

In [9]:
df[df["STATE"]=="AP"]

    CID      CNAME STATE DSG
1   200   SAGATIKA    AP  SE
3   400     ROSSUM    AP  TL
6   700  TEJASWANI    AP  SE
9   750        KVR    AP  PM
11  550    MOUNIKA    AP  PM
13  150    MADHVAI    AP  HR
15  950     ANJALI    AP  HR

In [10]:
df.loc[df["STATE"]=="AP"]

    CID      CNAME STATE DSG
1   200   SAGATIKA    AP  SE
3   400     ROSSUM    AP  TL
6   700  TEJASWANI    AP  SE
9   750        KVR    AP  PM
11  550    MOUNIKA    AP  PM
13  150    MADHVAI    AP  HR
15  950     ANJALI    AP  HR

In [11]:
df.loc[df["STATE"]=="AP"]["CNAME"]

1      SAGATIKA
3        ROSSUM
6     TEJASWANI
9           KVR
11      MOUNIKA
13      MADHVAI
15       ANJALI
Name: CNAME, dtype: object

In [12]:
len(df.loc[df["STATE"]=="AP"])

7

In [15]:
# DataFrameobj.loc[(compund condition),["Col Name"]]=Expression
df.loc[df["STATE"]=="AP",["STATE"]]="Andhara Pradesh"

In [16]:
print(df)

    CID      CNAME            STATE DSG
0   100      SUSMA               TS  SE
1   200   SAGATIKA  Andhara Pradesh  SE
2   300      LAXMI               TS  TL
3   400     ROSSUM  Andhara Pradesh  TL
4   500     NARESH            DELHI  PM
5   600      VINAY            DELHI   M
6   700  TEJASWANI  Andhara Pradesh  SE
7   800     FAZINA               TS  PM
8   900    SANSKAR            DELHI  SE
9   750        KVR  Andhara Pradesh  PM
10  650      RADHA             BANG  TL
11  550    MOUNIKA  Andhara Pradesh  PM
12  350    SIRISHA               TS  HR
13  150    MADHVAI  Andhara Pradesh  HR
14  450   JAYSHREE             BANG  HR
15  950     ANJALI  Andhara Pradesh  HR
16  250      KOMAL               TS  TL

In [18]:
df.columns

Index(['CID', 'CNAME', 'STATE', 'DSG'], dtype='object')

In [21]:
df.loc[df["DSG"]=="SE"]

   CID      CNAME            STATE DSG
0  100      SUSMA               TS  SE
1  200   SAGATIKA  Andhara Pradesh  SE
6  700  TEJASWANI  Andhara Pradesh  SE
8  900    SANSKAR            DELHI  SE

In [22]:
df.loc[(df["DSG"]=="SE") & (df["STATE"]=="TS")]

   CID  CNAME STATE DSG
0  100  SUSMA    TS  SE

In [24]:
df.loc[(df["DSG"]=="SE") & (df["STATE"]=="TS"),["DSG"]]="SR. SE"
print(df)

    CID      CNAME            STATE     DSG
0   100      SUSMA               TS  SR. SE
1   200   SAGATIKA  Andhara Pradesh      SE
2   300      LAXMI               TS      TL
3   400     ROSSUM  Andhara Pradesh      TL
4   500     NARESH            DELHI      PM
5   600      VINAY            DELHI       M
6   700  TEJASWANI  Andhara Pradesh      SE
7   800     FAZINA               TS      PM
8   900    SANSKAR            DELHI      SE
9   750        KVR  Andhara Pradesh      PM
10  650      RADHA             BANG      TL
11  550    MOUNIKA  Andhara Pradesh      PM
12  350    SIRISHA               TS      HR
13  150    MADHVAI  Andhara Pradesh      HR
14  450   JAYSHREE             BANG      HR
15  950     ANJALI  Andhara Pradesh      HR
16  250      KOMAL               TS      TL

In [25]:
df.loc[((df["DSG"]=="SR. SE") & (df["STATE"]=="TS")),["STATE","DSG"]]=\
["Telangana","Pythonist"]

In [26]:
print(df)

    CID      CNAME            STATE        DSG
0   100      SUSMA        Telangana  Pythonist
1   200   SAGATIKA  Andhara Pradesh         SE
2   300      LAXMI               TS         TL
3   400     ROSSUM  Andhara Pradesh         TL
4   500     NARESH            DELHI         PM
5   600      VINAY            DELHI          M
6   700  TEJASWANI  Andhara Pradesh         SE
7   800     FAZINA               TS         PM
8   900    SANSKAR            DELHI         SE
9   750        KVR  Andhara Pradesh         PM
10  650      RADHA             BANG         TL
11  550    MOUNIKA  Andhara Pradesh         PM
12  350    SIRISHA               TS         HR
13  150    MADHVAI  Andhara Pradesh         HR
14  450   JAYSHREE             BANG         HR
15  950     ANJALI  Andhara Pradesh         HR
16  250      KOMAL               TS         TL

In [29]:
# Find the nu,ber of People and their name who are living in BANG
df.loc[df["STATE"]=="BANG"]

    CID     CNAME STATE DSG
10  650     RADHA  BANG  TL
14  450  JAYSHREE  BANG  HR

In [32]:
df.loc[df["STATE"]=="BANG"]["CNAME"]

10       RADHA
14    JAYSHREE
Name: CNAME, dtype: object

In [33]:
# Number of peoples leaving in BANG
len(df.loc[df["STATE"]=="BANG"]["CNAME"])

2

In [34]:
# Get Student Data set into DataFrame
df=pd.read_csv("D:\\Akash\\Python\\KVR-PYTHON-PART-1\\PANDAS\\NOTES\\Student.csv")
print(df)

    htno     name  telugu  english  hindi  maths  science  social
0    100   Ramesh      50       60     66     98       66      55
1    101   Rajesh      45       67     34     67       66      78
2    102   Rossum      56       88     56     99       44      77
3    103     Raji      56       78     34     56       88      55
4    104   Kalyan      51       63     62     93       67      51
5    105  Karthik      48       62     39     68       65      88
6    106   Kambli      53       81     59     92       48      73
7    107  Praveen      46       88     74     86       78      45
8    108   Ganesh      53       62     76     88       76      35
9    109     Nags      55       77     44     77       86      58
10   110    Biswa      66       48     86     95       48      47
11   111   Ritchi      66       68     64     76       98      75
12   104   Kalyan      51       63     62     93       67      51
13   112  shareef      50       63     99     90       76      67
14   113     sonu      60       89     98     87       77      68
15   114   Rajesh      45       67     77     55       66      46
16   115   Rakesh      67       78     88     78       67      49

In [35]:
df["total"]=df["telugu"]+df["english"]+df["hindi"]+df["maths"]+df["science"]+df["social"]

In [36]:
print(df)

    htno     name  telugu  english  hindi  maths  science  social  total
0    100   Ramesh      50       60     66     98       66      55    395
1    101   Rajesh      45       67     34     67       66      78    357
2    102   Rossum      56       88     56     99       44      77    420
3    103     Raji      56       78     34     56       88      55    367
4    104   Kalyan      51       63     62     93       67      51    387
5    105  Karthik      48       62     39     68       65      88    370
6    106   Kambli      53       81     59     92       48      73    406
7    107  Praveen      46       88     74     86       78      45    417
8    108   Ganesh      53       62     76     88       76      35    390
9    109     Nags      55       77     44     77       86      58    397
10   110    Biswa      66       48     86     95       48      47    390
11   111   Ritchi      66       68     64     76       98      75    447
12   104   Kalyan      51       63     62     93       67      51    387
13   112  shareef      50       63     99     90       76      67    445
14   113     sonu      60       89     98     87       77      68    479
15   114   Rajesh      45       67     77     55       66      46    356
16   115   Rakesh      67       78     88     78       67      49    427

In [37]:
df["percent"]=round((df["total"]/600)*100,2)

In [38]:
print(df)

    htno     name  telugu  english  hindi  maths  science  social  total  \
0    100   Ramesh      50       60     66     98       66      55    395
1    101   Rajesh      45       67     34     67       66      78    357
2    102   Rossum      56       88     56     99       44      77    420
3    103     Raji      56       78     34     56       88      55    367
4    104   Kalyan      51       63     62     93       67      51    387
5    105  Karthik      48       62     39     68       65      88    370
6    106   Kambli      53       81     59     92       48      73    406
7    107  Praveen      46       88     74     86       78      45    417
8    108   Ganesh      53       62     76     88       76      35    390
9    109     Nags      55       77     44     77       86      58    397
10   110    Biswa      66       48     86     95       48      47    390
11   111   Ritchi      66       68     64     76       98      75    447
12   104   Kalyan      51       63     62     93       67      51    387
13   112  shareef      50       63     99     90       76      67    445
14   113     sonu      60       89     98     87       77      68    479
15   114   Rajesh      45       67     77     55       66      46    356
16   115   Rakesh      67       78     88     78       67      49    427

    percent
0     65.83
1     59.50
2     70.00
3     61.17
4     64.50
5     61.67
6     67.67
7     69.50
8     65.00
9     66.17
10    65.00
11    74.50
12    64.50
13    74.17
14    79.83
15    59.33
16    71.17

In [39]:
# Grading Rules
# Rule 1= perccent 100 --75--Distinction
# Rule 2=perccent 75 --65--First 
# Rule 3=perccent 65 --60--Second 
# Rule 4=perccent <60--Third

In [40]:
df["grade"]="Null"

In [41]:
print(df)

    htno     name  telugu  english  hindi  maths  science  social  total  \
0    100   Ramesh      50       60     66     98       66      55    395
1    101   Rajesh      45       67     34     67       66      78    357
2    102   Rossum      56       88     56     99       44      77    420
3    103     Raji      56       78     34     56       88      55    367
4    104   Kalyan      51       63     62     93       67      51    387
5    105  Karthik      48       62     39     68       65      88    370
6    106   Kambli      53       81     59     92       48      73    406
7    107  Praveen      46       88     74     86       78      45    417
8    108   Ganesh      53       62     76     88       76      35    390
9    109     Nags      55       77     44     77       86      58    397
10   110    Biswa      66       48     86     95       48      47    390
11   111   Ritchi      66       68     64     76       98      75    447
12   104   Kalyan      51       63     62     93       67      51    387
13   112  shareef      50       63     99     90       76      67    445
14   113     sonu      60       89     98     87       77      68    479
15   114   Rajesh      45       67     77     55       66      46    356
16   115   Rakesh      67       78     88     78       67      49    427

    percent grade
0     65.83  Null
1     59.50  Null
2     70.00  Null
3     61.17  Null
4     64.50  Null
5     61.67  Null
6     67.67  Null
7     69.50  Null
8     65.00  Null
9     66.17  Null
10    65.00  Null
11    74.50  Null
12    64.50  Null
13    74.17  Null
14    79.83  Null
15    59.33  Null
16    71.17  Null

In [43]:
df.loc[df["percent"]>=75]

,htno,name,telugu,english,hindi,maths,science,social,total,percent,grade
14,113,sonu,60,89,98,87,77,68,479,79.83,Null

In [65]:
df.loc[df["percent"]>=75,["grade"]]="DISTINCION"

In [66]:
print(df)

    htno     name  telugu  english  hindi  maths  science  social  total  \
0    100   Ramesh      50       60     66     98       66      55    395
1    101   Rajesh      45       67     34     67       66      78    357
2    102   Rossum      56       88     56     99       44      77    420
3    103     Raji      56       78     34     56       88      55    367
4    104   Kalyan      51       63     62     93       67      51    387
5    105  Karthik      48       62     39     68       65      88    370
6    106   Kambli      53       81     59     92       48      73    406
7    107  Praveen      46       88     74     86       78      45    417
8    108   Ganesh      53       62     76     88       76      35    390
9    109     Nags      55       77     44     77       86      58    397
10   110    Biswa      66       48     86     95       48      47    390
11   111   Ritchi      66       68     64     76       98      75    447
12   104   Kalyan      51       63     62     93       67      51    387
13   112  shareef      50       63     99     90       76      67    445
14   113     sonu      60       89     98     87       77      68    479
15   114   Rajesh      45       67     77     55       66      46    356
16   115   Rakesh      67       78     88     78       67      49    427

    percent       grade
0     65.83       THIRD
1     59.50       THIRD
2     70.00       THIRD
3     61.17       THIRD
4     64.50       THIRD
5     61.67       THIRD
6     67.67       THIRD
7     69.50       THIRD
8     65.00       THIRD
9     66.17       THIRD
10    65.00       THIRD
11    74.50       THIRD
12    64.50       THIRD
13    74.17       THIRD
14    79.83  DISTINCION
15    59.33       THIRD
16    71.17       THIRD

In [67]:
df.loc[df["grade"]=="DISTINCION"]

,htno,name,telugu,english,hindi,maths,science,social,total,percent,grade
14,113,sonu,60,89,98,87,77,68,479,79.83,DISTINCION

In [68]:
df.loc[((df["percent"]>=65)&(df["percent"]<75)),["grade"]]="FIRST"

In [69]:
print(df)

    htno     name  telugu  english  hindi  maths  science  social  total  \
0    100   Ramesh      50       60     66     98       66      55    395
1    101   Rajesh      45       67     34     67       66      78    357
2    102   Rossum      56       88     56     99       44      77    420
3    103     Raji      56       78     34     56       88      55    367
4    104   Kalyan      51       63     62     93       67      51    387
5    105  Karthik      48       62     39     68       65      88    370
6    106   Kambli      53       81     59     92       48      73    406
7    107  Praveen      46       88     74     86       78      45    417
8    108   Ganesh      53       62     76     88       76      35    390
9    109     Nags      55       77     44     77       86      58    397
10   110    Biswa      66       48     86     95       48      47    390
11   111   Ritchi      66       68     64     76       98      75    447
12   104   Kalyan      51       63     62     93       67      51    387
13   112  shareef      50       63     99     90       76      67    445
14   113     sonu      60       89     98     87       77      68    479
15   114   Rajesh      45       67     77     55       66      46    356
16   115   Rakesh      67       78     88     78       67      49    427

    percent       grade
0     65.83       FIRST
1     59.50       THIRD
2     70.00       FIRST
3     61.17       THIRD
4     64.50       THIRD
5     61.67       THIRD
6     67.67       FIRST
7     69.50       FIRST
8     65.00       FIRST
9     66.17       FIRST
10    65.00       FIRST
11    74.50       FIRST
12    64.50       THIRD
13    74.17       FIRST
14    79.83  DISTINCION
15    59.33       THIRD
16    71.17       FIRST

In [70]:
df[df["grade"]=="FIRST"]

,htno,name,telugu,english,hindi,maths,science,social,total,percent,grade
0,100,Ramesh,50,60,66,98,66,55,395,65.83,FIRST
2,102,Rossum,56,88,56,99,44,77,420,70.00,FIRST
6,106,Kambli,53,81,59,92,48,73,406,67.67,FIRST
7,107,Praveen,46,88,74,86,78,45,417,69.50,FIRST
8,108,Ganesh,53,62,76,88,76,35,390,65.00,FIRST
9,109,Nags,55,77,44,77,86,58,397,66.17,FIRST
10,110,Biswa,66,48,86,95,48,47,390,65.00,FIRST
11,111,Ritchi,66,68,64,76,98,75,447,74.50,FIRST
13,112,shareef,50,63,99,90,76,67,445,74.17,FIRST
16,115,Rakesh,67,78,88,78,67,49,427,71.17,FIRST

In [71]:
df[df["grade"]=="FIRST"][["htno","name"]]

    htno     name
0    100   Ramesh
2    102   Rossum
6    106   Kambli
7    107  Praveen
8    108   Ganesh
9    109     Nags
10   110    Biswa
11   111   Ritchi
13   112  shareef
16   115   Rakesh

In [72]:
len(df[df["grade"]=="FIRST"])

10

In [73]:
df.loc[((df["percent"]>=60)&(df["percent"]<65)),["grade"]]="SECOND"

In [74]:
print(df)

    htno     name  telugu  english  hindi  maths  science  social  total  \
0    100   Ramesh      50       60     66     98       66      55    395
1    101   Rajesh      45       67     34     67       66      78    357
2    102   Rossum      56       88     56     99       44      77    420
3    103     Raji      56       78     34     56       88      55    367
4    104   Kalyan      51       63     62     93       67      51    387
5    105  Karthik      48       62     39     68       65      88    370
6    106   Kambli      53       81     59     92       48      73    406
7    107  Praveen      46       88     74     86       78      45    417
8    108   Ganesh      53       62     76     88       76      35    390
9    109     Nags      55       77     44     77       86      58    397
10   110    Biswa      66       48     86     95       48      47    390
11   111   Ritchi      66       68     64     76       98      75    447
12   104   Kalyan      51       63     62     93       67      51    387
13   112  shareef      50       63     99     90       76      67    445
14   113     sonu      60       89     98     87       77      68    479
15   114   Rajesh      45       67     77     55       66      46    356
16   115   Rakesh      67       78     88     78       67      49    427

    percent       grade
0     65.83       FIRST
1     59.50       THIRD
2     70.00       FIRST
3     61.17      SECOND
4     64.50      SECOND
5     61.67      SECOND
6     67.67       FIRST
7     69.50       FIRST
8     65.00       FIRST
9     66.17       FIRST
10    65.00       FIRST
11    74.50       FIRST
12    64.50      SECOND
13    74.17       FIRST
14    79.83  DISTINCION
15    59.33       THIRD
16    71.17       FIRST

In [75]:
df.loc[(df["percent"]<60),["grade"]]="THIRD"

In [76]:
print(df)

    htno     name  telugu  english  hindi  maths  science  social  total  \
0    100   Ramesh      50       60     66     98       66      55    395
1    101   Rajesh      45       67     34     67       66      78    357
2    102   Rossum      56       88     56     99       44      77    420
3    103     Raji      56       78     34     56       88      55    367
4    104   Kalyan      51       63     62     93       67      51    387
5    105  Karthik      48       62     39     68       65      88    370
6    106   Kambli      53       81     59     92       48      73    406
7    107  Praveen      46       88     74     86       78      45    417
8    108   Ganesh      53       62     76     88       76      35    390
9    109     Nags      55       77     44     77       86      58    397
10   110    Biswa      66       48     86     95       48      47    390
11   111   Ritchi      66       68     64     76       98      75    447
12   104   Kalyan      51       63     62     93       67      51    387
13   112  shareef      50       63     99     90       76      67    445
14   113     sonu      60       89     98     87       77      68    479
15   114   Rajesh      45       67     77     55       66      46    356
16   115   Rakesh      67       78     88     78       67      49    427

    percent       grade
0     65.83       FIRST
1     59.50       THIRD
2     70.00       FIRST
3     61.17      SECOND
4     64.50      SECOND
5     61.67      SECOND
6     67.67       FIRST
7     69.50       FIRST
8     65.00       FIRST
9     66.17       FIRST
10    65.00       FIRST
11    74.50       FIRST
12    64.50      SECOND
13    74.17       FIRST
14    79.83  DISTINCION
15    59.33       THIRD
16    71.17       FIRST

In [79]:
df.loc[df["grade"]=="THIRD"]

,htno,name,telugu,english,hindi,maths,science,social,total,percent,grade
1,101,Rajesh,45,67,34,67,66,78,357,59.50,THIRD
15,114,Rajesh,45,67,77,55,66,46,356,59.33,THIRD

In [81]:
# EXPORT DATA to DADtframe to csv fiile
df.to_csv("D:\\Akash\\Python\\KVR-PYTHON-PART-1\\PANDAS\\NOTES\\XthfinalResult.csv")

In [82]:
# EXPORT DATA to DADtframe to Excel fiile
df.to_excel("D:\\Akash\\Python\\KVR-PYTHON-PART-1\\PANDAS\\NOTES\\Xth.xlsx")