In [1]:
import pandas as pd
import numpy as np

In [2]:
d={"First":[100,200,300,np.nan],"Second":[150,np.nan,250,np.nan],
  "Third":[np.nan,250,120,100]}
print(d,type(d))

{'First': [100, 200, 300, nan], 'Second': [150, nan, 250, nan], 'Third': [nan, 250, 120, 100]} <class 'dict'>

In [3]:
for k,v in d.items():
    print(k,"--->",v)

First ---> [100, 200, 300, nan]
Second ---> [150, nan, 250, nan]
Third ---> [nan, 250, 120, 100]

In [4]:
df=pd.DataFrame(d)
print(df)

   First  Second  Third
0  100.0   150.0    NaN
1  200.0     NaN  250.0
2  300.0   250.0  120.0
3    NaN     NaN  100.0

In [5]:
# Find Missing Value using isnull()
# Syntax : DataFrameobj.isnull()
df.isnull()

   First  Second  Third
0  False   False   True
1  False    True  False
2  False   False  False
3   True    True  False

In [6]:
len(df.isnull())

4

In [7]:
df.isnull().sum()

First     1
Second    2
Third     1
dtype: int64

In [8]:
df.isnull().count().nunique()

1

In [9]:
print(df)

   First  Second  Third
0  100.0   150.0    NaN
1  200.0     NaN  250.0
2  300.0   250.0  120.0
3    NaN     NaN  100.0

In [10]:
df.notnull()

   First  Second  Third
0   True    True  False
1   True   False   True
2   True    True   True
3  False   False   True

In [33]:
# print("Print Not null; Values=",len(df.notnull()))
print("Print Not null; Values=",(df.size-len(df.notnull())))
print("Print  null; Values=",len(df.isnull()))
print("Print Not null; Values=",len(df.notnull()))

Print Not null; Values= 2
Print  null; Values= 1
Print Not null; Values= 1

In [12]:
print(df)

   First  Second  Third
0  100.0   150.0    NaN
1  200.0     NaN  250.0
2  300.0   250.0  120.0
3    NaN     NaN  100.0

In [13]:
df.isnull()

   First  Second  Third
0  False   False   True
1  False    True  False
2  False   False  False
3   True    True  False

In [14]:
# Fill nan values wiith 0
# to fill nan values with 0, we uses fillna()
# syntax: df.fillna(value)

In [15]:
df.fillna(0)

   First  Second  Third
0  100.0   150.0    0.0
1  200.0     0.0  250.0
2  300.0   250.0  120.0
3    0.0     0.0  100.0

In [16]:
print(df)

   First  Second  Third
0  100.0   150.0    NaN
1  200.0     NaN  250.0
2  300.0   250.0  120.0
3    NaN     NaN  100.0

In [17]:
df=df.fillna(0)

In [18]:
print(df)

   First  Second  Third
0  100.0   150.0    0.0
1  200.0     0.0  250.0
2  300.0   250.0  120.0
3    0.0     0.0  100.0

In [19]:
d={"First":[100,200,300,np.nan],"Second":[150,np.nan,250,np.nan],
  "Third":[np.nan,250,120,100]}
df=pd.DataFrame(d)
print(df)

   First  Second  Third
0  100.0   150.0    NaN
1  200.0     NaN  250.0
2  300.0   250.0  120.0
3    NaN     NaN  100.0

In [20]:
df.fillna(0.0,inplace=True)
print(df)

   First  Second  Third
0  100.0   150.0    0.0
1  200.0     0.0  250.0
2  300.0   250.0  120.0
3    0.0     0.0  100.0

In [21]:
d={"First":[100,200,300,np.nan],"Second":[150,np.nan,250,np.nan],
  "Third":[np.nan,250,120,100]}
df=pd.DataFrame(d)
print(df)

   First  Second  Third
0  100.0   150.0    NaN
1  200.0     NaN  250.0
2  300.0   250.0  120.0
3    NaN     NaN  100.0

In [22]:
# Fill Nan values with 5.0
df.fillna(5.0,inplace=True)
print(df)

   First  Second  Third
0  100.0   150.0    5.0
1  200.0     5.0  250.0
2  300.0   250.0  120.0
3    5.0     5.0  100.0

In [23]:
d={"First":[100,200,300,np.nan],"Second":[150,np.nan,250,np.nan],
  "Third":[np.nan,250,120,100]}
df=pd.DataFrame(d)
print(df)

   First  Second  Third
0  100.0   150.0    NaN
1  200.0     NaN  250.0
2  300.0   250.0  120.0
3    NaN     NaN  100.0

In [24]:
# Fill nan values wiith 0
# to fill nan values with 0, we can s=aslo use replace(to_replace,value)
# syntax: df.replace(to_replace,value)

In [25]:
df.replace(to_replace=np.nan,value=0.0)

   First  Second  Third
0  100.0   150.0    0.0
1  200.0     0.0  250.0
2  300.0   250.0  120.0
3    0.0     0.0  100.0

In [26]:
d={"First":[100,200,300,np.nan],"Second":[150,np.nan,250,np.nan],
  "Third":[np.nan,250,120,100]}
df=pd.DataFrame(d)
print(df)

   First  Second  Third
0  100.0   150.0    NaN
1  200.0     NaN  250.0
2  300.0   250.0  120.0
3    NaN     NaN  100.0

In [27]:
# Drop Nan Values from DataFrameobj
df.dropna()

   First  Second  Third
2  300.0   250.0  120.0

In [28]:
print(df)

   First  Second  Third
0  100.0   150.0    NaN
1  200.0     NaN  250.0
2  300.0   250.0  120.0
3    NaN     NaN  100.0

In [29]:
# Drop Nan Values from DataFrameobj
df.dropna(inplace=True)

In [30]:
print(df)

   First  Second  Third
2  300.0   250.0  120.0