In [1]:
import pandas as pd

In [2]:
# Get Student Data set into DataFrame
df=pd.read_csv("D:\\Akash\\Python\\KVR-PYTHON-PART-1\\PANDAS\\NOTES\\Student.csv")
print(df)

    htno     name  telugu  english  hindi  maths  science  social
0    100   Ramesh      50       60     66     98       66      55
1    101   Rajesh      45       67     34     67       66      78
2    102   Rossum      56       88     56     99       44      77
3    103     Raji      56       78     34     56       88      55
4    104   Kalyan      51       63     62     93       67      51
5    105  Karthik      48       62     39     68       65      88
6    106   Kambli      53       81     59     92       48      73
7    107  Praveen      46       88     74     86       78      45
8    108   Ganesh      53       62     76     88       76      35
9    109     Nags      55       77     44     77       86      58
10   110    Biswa      66       48     86     95       48      47
11   111   Ritchi      66       68     64     76       98      75
12   104   Kalyan      51       63     62     93       67      51
13   112  shareef      50       63     99     90       76      67
14   113     sonu      60       89     98     87       77      68
15   114   Rajesh      45       67     77     55       66      46
16   115   Rakesh      67       78     88     78       67      49

In [3]:
# Remove Hindi Column
df.drop(columns="hindi".rstrip())

    htno     name  telugu  english  maths  science  social
0    100   Ramesh      50       60     98       66      55
1    101   Rajesh      45       67     67       66      78
2    102   Rossum      56       88     99       44      77
3    103     Raji      56       78     56       88      55
4    104   Kalyan      51       63     93       67      51
5    105  Karthik      48       62     68       65      88
6    106   Kambli      53       81     92       48      73
7    107  Praveen      46       88     86       78      45
8    108   Ganesh      53       62     88       76      35
9    109     Nags      55       77     77       86      58
10   110    Biswa      66       48     95       48      47
11   111   Ritchi      66       68     76       98      75
12   104   Kalyan      51       63     93       67      51
13   112  shareef      50       63     90       76      67
14   113     sonu      60       89     87       77      68
15   114   Rajesh      45       67     55       66      46
16   115   Rakesh      67       78     78       67      49

In [6]:
# Remove multiple Columns
df.drop(columns=["hindi","telugu"])

    htno     name  english  maths  science  social
0    100   Ramesh       60     98       66      55
1    101   Rajesh       67     67       66      78
2    102   Rossum       88     99       44      77
3    103     Raji       78     56       88      55
4    104   Kalyan       63     93       67      51
5    105  Karthik       62     68       65      88
6    106   Kambli       81     92       48      73
7    107  Praveen       88     86       78      45
8    108   Ganesh       62     88       76      35
9    109     Nags       77     77       86      58
10   110    Biswa       48     95       48      47
11   111   Ritchi       68     76       98      75
12   104   Kalyan       63     93       67      51
13   112  shareef       63     90       76      67
14   113     sonu       89     87       77      68
15   114   Rajesh       67     55       66      46
16   115   Rakesh       78     78       67      49

In [7]:
print(df)

    htno     name  telugu  english  hindi  maths  science  social
0    100   Ramesh      50       60     66     98       66      55
1    101   Rajesh      45       67     34     67       66      78
2    102   Rossum      56       88     56     99       44      77
3    103     Raji      56       78     34     56       88      55
4    104   Kalyan      51       63     62     93       67      51
5    105  Karthik      48       62     39     68       65      88
6    106   Kambli      53       81     59     92       48      73
7    107  Praveen      46       88     74     86       78      45
8    108   Ganesh      53       62     76     88       76      35
9    109     Nags      55       77     44     77       86      58
10   110    Biswa      66       48     86     95       48      47
11   111   Ritchi      66       68     64     76       98      75
12   104   Kalyan      51       63     62     93       67      51
13   112  shareef      50       63     99     90       76      67
14   113     sonu      60       89     98     87       77      68
15   114   Rajesh      45       67     77     55       66      46
16   115   Rakesh      67       78     88     78       67      49

In [8]:
# Remove multiple Columns
df.drop(columns=["hindi","telugu"],inplace=True)

In [9]:
print(df)

    htno     name  english  maths  science  social
0    100   Ramesh       60     98       66      55
1    101   Rajesh       67     67       66      78
2    102   Rossum       88     99       44      77
3    103     Raji       78     56       88      55
4    104   Kalyan       63     93       67      51
5    105  Karthik       62     68       65      88
6    106   Kambli       81     92       48      73
7    107  Praveen       88     86       78      45
8    108   Ganesh       62     88       76      35
9    109     Nags       77     77       86      58
10   110    Biswa       48     95       48      47
11   111   Ritchi       68     76       98      75
12   104   Kalyan       63     93       67      51
13   112  shareef       63     90       76      67
14   113     sonu       89     87       77      68
15   114   Rajesh       67     55       66      46
16   115   Rakesh       78     78       67      49

In [12]:
# # Remove Columns name from DataFrame base on column number
df.drop(columns=df.columns[5])

    htno     name  english  maths  science
0    100   Ramesh       60     98       66
1    101   Rajesh       67     67       66
2    102   Rossum       88     99       44
3    103     Raji       78     56       88
4    104   Kalyan       63     93       67
5    105  Karthik       62     68       65
6    106   Kambli       81     92       48
7    107  Praveen       88     86       78
8    108   Ganesh       62     88       76
9    109     Nags       77     77       86
10   110    Biswa       48     95       48
11   111   Ritchi       68     76       98
12   104   Kalyan       63     93       67
13   112  shareef       63     90       76
14   113     sonu       89     87       77
15   114   Rajesh       67     55       66
16   115   Rakesh       78     78       67

In [13]:
# # Remove Columns name from DataFrame base on column number
df.drop(columns=df.columns[5],inplace=True)

In [14]:
print(df)

    htno     name  english  maths  science
0    100   Ramesh       60     98       66
1    101   Rajesh       67     67       66
2    102   Rossum       88     99       44
3    103     Raji       78     56       88
4    104   Kalyan       63     93       67
5    105  Karthik       62     68       65
6    106   Kambli       81     92       48
7    107  Praveen       88     86       78
8    108   Ganesh       62     88       76
9    109     Nags       77     77       86
10   110    Biswa       48     95       48
11   111   Ritchi       68     76       98
12   104   Kalyan       63     93       67
13   112  shareef       63     90       76
14   113     sonu       89     87       77
15   114   Rajesh       67     55       66
16   115   Rakesh       78     78       67

In [16]:
# Remove Columns name from DataFrame base on column number
df.drop(columns=df.columns[[2,4]],inplace=True)

In [17]:
print(df)

    htno     name  maths
0    100   Ramesh     98
1    101   Rajesh     67
2    102   Rossum     99
3    103     Raji     56
4    104   Kalyan     93
5    105  Karthik     68
6    106   Kambli     92
7    107  Praveen     86
8    108   Ganesh     88
9    109     Nags     77
10   110    Biswa     95
11   111   Ritchi     76
12   104   Kalyan     93
13   112  shareef     90
14   113     sonu     87
15   114   Rajesh     55
16   115   Rakesh     78