In [1]:
import pandas as pd

In [3]:
# Get Student Data set into DataFrame
df=pd.read_csv("D:\\Akash\\Python\\KVR-PYTHON-PART-1\\PANDAS\\NOTES\\Student.csv")
print(df)

    htno     name  telugu  english  hindi  maths  science  social
0    100   Ramesh      50       60     66     98       66      55
1    101   Rajesh      45       67     34     67       66      78
2    102   Rossum      56       88     56     99       44      77
3    103     Raji      56       78     34     56       88      55
4    104   Kalyan      51       63     62     93       67      51
5    105  Karthik      48       62     39     68       65      88
6    106   Kambli      53       81     59     92       48      73
7    107  Praveen      46       88     74     86       78      45
8    108   Ganesh      53       62     76     88       76      35
9    109     Nags      55       77     44     77       86      58
10   110    Biswa      66       48     86     95       48      47
11   111   Ritchi      66       68     64     76       98      75
12   104   Kalyan      51       63     62     93       67      51
13   112  shareef      50       63     99     90       76      67
14   113     sonu      60       89     98     87       77      68
15   114   Rajesh      45       67     77     55       66      46
16   115   Rakesh      67       78     88     78       67      49

In [7]:
# Sort The Name of Student in Assending order
df.sort_values(["name"])

    htno     name  telugu  english  hindi  maths  science  social
10   110    Biswa      66       48     86     95       48      47
8    108   Ganesh      53       62     76     88       76      35
12   104   Kalyan      51       63     62     93       67      51
4    104   Kalyan      51       63     62     93       67      51
6    106   Kambli      53       81     59     92       48      73
5    105  Karthik      48       62     39     68       65      88
9    109     Nags      55       77     44     77       86      58
7    107  Praveen      46       88     74     86       78      45
1    101   Rajesh      45       67     34     67       66      78
15   114   Rajesh      45       67     77     55       66      46
3    103     Raji      56       78     34     56       88      55
16   115   Rakesh      67       78     88     78       67      49
0    100   Ramesh      50       60     66     98       66      55
11   111   Ritchi      66       68     64     76       98      75
2    102   Rossum      56       88     56     99       44      77
13   112  shareef      50       63     99     90       76      67
14   113     sonu      60       89     98     87       77      68

In [6]:
print(df)

    htno     name  telugu  english  hindi  maths  science  social
0    100   Ramesh      50       60     66     98       66      55
1    101   Rajesh      45       67     34     67       66      78
2    102   Rossum      56       88     56     99       44      77
3    103     Raji      56       78     34     56       88      55
4    104   Kalyan      51       63     62     93       67      51
5    105  Karthik      48       62     39     68       65      88
6    106   Kambli      53       81     59     92       48      73
7    107  Praveen      46       88     74     86       78      45
8    108   Ganesh      53       62     76     88       76      35
9    109     Nags      55       77     44     77       86      58
10   110    Biswa      66       48     86     95       48      47
11   111   Ritchi      66       68     64     76       98      75
12   104   Kalyan      51       63     62     93       67      51
13   112  shareef      50       63     99     90       76      67
14   113     sonu      60       89     98     87       77      68
15   114   Rajesh      45       67     77     55       66      46
16   115   Rakesh      67       78     88     78       67      49

In [8]:
# Sort The Name of Student in Assending order
df.sort_values(["name"])[::-1]

    htno     name  telugu  english  hindi  maths  science  social
14   113     sonu      60       89     98     87       77      68
13   112  shareef      50       63     99     90       76      67
2    102   Rossum      56       88     56     99       44      77
11   111   Ritchi      66       68     64     76       98      75
0    100   Ramesh      50       60     66     98       66      55
16   115   Rakesh      67       78     88     78       67      49
3    103     Raji      56       78     34     56       88      55
15   114   Rajesh      45       67     77     55       66      46
1    101   Rajesh      45       67     34     67       66      78
7    107  Praveen      46       88     74     86       78      45
9    109     Nags      55       77     44     77       86      58
5    105  Karthik      48       62     39     68       65      88
6    106   Kambli      53       81     59     92       48      73
4    104   Kalyan      51       63     62     93       67      51
12   104   Kalyan      51       63     62     93       67      51
8    108   Ganesh      53       62     76     88       76      35
10   110    Biswa      66       48     86     95       48      47

In [10]:
# Sort The Name of Student in Assending order
df.sort_values(["name"],ascending=False)

    htno     name  telugu  english  hindi  maths  science  social
14   113     sonu      60       89     98     87       77      68
13   112  shareef      50       63     99     90       76      67
2    102   Rossum      56       88     56     99       44      77
11   111   Ritchi      66       68     64     76       98      75
0    100   Ramesh      50       60     66     98       66      55
16   115   Rakesh      67       78     88     78       67      49
3    103     Raji      56       78     34     56       88      55
1    101   Rajesh      45       67     34     67       66      78
15   114   Rajesh      45       67     77     55       66      46
7    107  Praveen      46       88     74     86       78      45
9    109     Nags      55       77     44     77       86      58
5    105  Karthik      48       62     39     68       65      88
6    106   Kambli      53       81     59     92       48      73
12   104   Kalyan      51       63     62     93       67      51
4    104   Kalyan      51       63     62     93       67      51
8    108   Ganesh      53       62     76     88       76      35
10   110    Biswa      66       48     86     95       48      47

In [11]:
# Sort The Name of Student in Assending order
df.sort_values(["name"],ascending=False,inplace=True)

In [12]:
print(df)

    htno     name  telugu  english  hindi  maths  science  social
14   113     sonu      60       89     98     87       77      68
13   112  shareef      50       63     99     90       76      67
2    102   Rossum      56       88     56     99       44      77
11   111   Ritchi      66       68     64     76       98      75
0    100   Ramesh      50       60     66     98       66      55
16   115   Rakesh      67       78     88     78       67      49
3    103     Raji      56       78     34     56       88      55
1    101   Rajesh      45       67     34     67       66      78
15   114   Rajesh      45       67     77     55       66      46
7    107  Praveen      46       88     74     86       78      45
9    109     Nags      55       77     44     77       86      58
5    105  Karthik      48       62     39     68       65      88
6    106   Kambli      53       81     59     92       48      73
12   104   Kalyan      51       63     62     93       67      51
4    104   Kalyan      51       63     62     93       67      51
8    108   Ganesh      53       62     76     88       76      35
10   110    Biswa      66       48     86     95       48      47

In [13]:
# Sort The Name of Student in Assending order
df.sort_values(["maths"],inplace=True)

In [14]:
print(df)

    htno     name  telugu  english  hindi  maths  science  social
15   114   Rajesh      45       67     77     55       66      46
3    103     Raji      56       78     34     56       88      55
1    101   Rajesh      45       67     34     67       66      78
5    105  Karthik      48       62     39     68       65      88
11   111   Ritchi      66       68     64     76       98      75
9    109     Nags      55       77     44     77       86      58
16   115   Rakesh      67       78     88     78       67      49
7    107  Praveen      46       88     74     86       78      45
14   113     sonu      60       89     98     87       77      68
8    108   Ganesh      53       62     76     88       76      35
13   112  shareef      50       63     99     90       76      67
6    106   Kambli      53       81     59     92       48      73
12   104   Kalyan      51       63     62     93       67      51
4    104   Kalyan      51       63     62     93       67      51
10   110    Biswa      66       48     86     95       48      47
0    100   Ramesh      50       60     66     98       66      55
2    102   Rossum      56       88     56     99       44      77

In [17]:
# Get Higest securde math makrs and name
df.tail(1)[["name","maths"]]

     name  maths
2  Rossum     99

In [23]:
df[-2:][["name","maths"]]

     name  maths
0  Ramesh     98
2  Rossum     99

In [24]:
df[-2:][["name","maths"]][::-1]

     name  maths
2  Rossum     99
0  Ramesh     98

In [25]:
print(df)

    htno     name  telugu  english  hindi  maths  science  social
15   114   Rajesh      45       67     77     55       66      46
3    103     Raji      56       78     34     56       88      55
1    101   Rajesh      45       67     34     67       66      78
5    105  Karthik      48       62     39     68       65      88
11   111   Ritchi      66       68     64     76       98      75
9    109     Nags      55       77     44     77       86      58
16   115   Rakesh      67       78     88     78       67      49
7    107  Praveen      46       88     74     86       78      45
14   113     sonu      60       89     98     87       77      68
8    108   Ganesh      53       62     76     88       76      35
13   112  shareef      50       63     99     90       76      67
6    106   Kambli      53       81     59     92       48      73
12   104   Kalyan      51       63     62     93       67      51
4    104   Kalyan      51       63     62     93       67      51
10   110    Biswa      66       48     86     95       48      47
0    100   Ramesh      50       60     66     98       66      55
2    102   Rossum      56       88     56     99       44      77

In [27]:
# find Second Least Marks in Math
df[1:2]["name"]

3    Raji
Name: name, dtype: object

In [28]:
df["tot"]=df["telugu"]+df["english"]+df["hindi"]+df["maths"]+df["science"]+df["social"]

In [29]:
print(df)

    htno     name  telugu  english  hindi  maths  science  social  tot
15   114   Rajesh      45       67     77     55       66      46  356
3    103     Raji      56       78     34     56       88      55  367
1    101   Rajesh      45       67     34     67       66      78  357
5    105  Karthik      48       62     39     68       65      88  370
11   111   Ritchi      66       68     64     76       98      75  447
9    109     Nags      55       77     44     77       86      58  397
16   115   Rakesh      67       78     88     78       67      49  427
7    107  Praveen      46       88     74     86       78      45  417
14   113     sonu      60       89     98     87       77      68  479
8    108   Ganesh      53       62     76     88       76      35  390
13   112  shareef      50       63     99     90       76      67  445
6    106   Kambli      53       81     59     92       48      73  406
12   104   Kalyan      51       63     62     93       67      51  387
4    104   Kalyan      51       63     62     93       67      51  387
10   110    Biswa      66       48     86     95       48      47  390
0    100   Ramesh      50       60     66     98       66      55  395
2    102   Rossum      56       88     56     99       44      77  420

In [30]:
df.sort_values(["tot"],inplace=True)

In [31]:
print(df)

    htno     name  telugu  english  hindi  maths  science  social  tot
15   114   Rajesh      45       67     77     55       66      46  356
1    101   Rajesh      45       67     34     67       66      78  357
3    103     Raji      56       78     34     56       88      55  367
5    105  Karthik      48       62     39     68       65      88  370
12   104   Kalyan      51       63     62     93       67      51  387
4    104   Kalyan      51       63     62     93       67      51  387
10   110    Biswa      66       48     86     95       48      47  390
8    108   Ganesh      53       62     76     88       76      35  390
0    100   Ramesh      50       60     66     98       66      55  395
9    109     Nags      55       77     44     77       86      58  397
6    106   Kambli      53       81     59     92       48      73  406
7    107  Praveen      46       88     74     86       78      45  417
2    102   Rossum      56       88     56     99       44      77  420
16   115   Rakesh      67       78     88     78       67      49  427
13   112  shareef      50       63     99     90       76      67  445
11   111   Ritchi      66       68     64     76       98      75  447
14   113     sonu      60       89     98     87       77      68  479

In [33]:
# Get five Top Higest scorer
df.tail()[::-1][["name","tot"]]

       name  tot
14     sonu  479
11   Ritchi  447
13  shareef  445
16   Rakesh  427
2    Rossum  420