In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("D:\\Akash\\Python\\KVR-PYTHON-PART-1\\PANDAS\\NOTES\\peoples.csv")
print(df)

    CID      CNAME  STATE DSG
0   100      SUSMA     TS  SE
1   200   SAGATIKA     AP  SE
2   300      LAXMI     TS  TL
3   400     ROSSUM     AP  TL
4   500     NARESH  DELHI  PM
5   600      VINAY  DELHI   M
6   700  TEJASWANI     AP  SE
7   800     FAZINA     TS  PM
8   900    SANSKAR  DELHI  SE
9   750        KVR     AP  PM
10  650      RADHA   BANG  TL
11  550    MOUNIKA     AP  PM
12  350    SIRISHA     TS  HR
13  150    MADHVAI     AP  HR
14  450   JAYSHREE   BANG  HR
15  950     ANJALI     AP  HR
16  250      KOMAL     TS  TL

In [4]:
# Get the peoples data State wise
gby=df.groupby("STATE")
print("Tpye of gby",type(gby))
print("Content of gby",gby)

Tpye of gby <class 'pandas.core.groupby.generic.DataFrameGroupBy'>
Content of gby <pandas.core.groupby.generic.DataFrameGroupBy object at 0x00000174F7557D90>

In [6]:
# Get the Data peoples with State wise
gby=df.groupby("STATE")
print("="*50)
for gn,gninfo in gby:
    print("State Name :{}".format(gn))
    print("Peoples Data:")
    print("{}".format(gninfo))
    print("="*50)

==================================================
State Name :AP
Peoples Data:
    CID      CNAME STATE DSG
1   200   SAGATIKA    AP  SE
3   400     ROSSUM    AP  TL
6   700  TEJASWANI    AP  SE
9   750        KVR    AP  PM
11  550    MOUNIKA    AP  PM
13  150    MADHVAI    AP  HR
15  950     ANJALI    AP  HR
==================================================
State Name :BANG
Peoples Data:
    CID     CNAME STATE DSG
10  650     RADHA  BANG  TL
14  450  JAYSHREE  BANG  HR
==================================================
State Name :DELHI
Peoples Data:
   CID    CNAME  STATE DSG
4  500   NARESH  DELHI  PM
5  600    VINAY  DELHI   M
8  900  SANSKAR  DELHI  SE
==================================================
State Name :TS
Peoples Data:
    CID    CNAME STATE DSG
0   100    SUSMA    TS  SE
2   300    LAXMI    TS  TL
7   800   FAZINA    TS  PM
12  350  SIRISHA    TS  HR
16  250    KOMAL    TS  TL
==================================================

In [7]:
# Get the Data peoples with State wise
print("="*50)
for gn,gninfo in df.groupby("STATE"):
    print("State Name :{}".format(gn))
    print("Peoples Data:")
    print("{}".format(gninfo))
    print("="*50)

==================================================
State Name :AP
Peoples Data:
    CID      CNAME STATE DSG
1   200   SAGATIKA    AP  SE
3   400     ROSSUM    AP  TL
6   700  TEJASWANI    AP  SE
9   750        KVR    AP  PM
11  550    MOUNIKA    AP  PM
13  150    MADHVAI    AP  HR
15  950     ANJALI    AP  HR
==================================================
State Name :BANG
Peoples Data:
    CID     CNAME STATE DSG
10  650     RADHA  BANG  TL
14  450  JAYSHREE  BANG  HR
==================================================
State Name :DELHI
Peoples Data:
   CID    CNAME  STATE DSG
4  500   NARESH  DELHI  PM
5  600    VINAY  DELHI   M
8  900  SANSKAR  DELHI  SE
==================================================
State Name :TS
Peoples Data:
    CID    CNAME STATE DSG
0   100    SUSMA    TS  SE
2   300    LAXMI    TS  TL
7   800   FAZINA    TS  PM
12  350  SIRISHA    TS  HR
16  250    KOMAL    TS  TL
==================================================

In [8]:
gby.first()

       CID     CNAME DSG
STATE
AP     200  SAGATIKA  SE
BANG   650     RADHA  TL
DELHI  500    NARESH  PM
TS     100     SUSMA  SE

In [9]:
gby.last()

       CID     CNAME DSG
STATE
AP     950    ANJALI  HR
BANG   450  JAYSHREE  HR
DELHI  900   SANSKAR  SE
TS     250     KOMAL  TL

In [10]:
gby.nth(3)

    CID    CNAME STATE DSG
9   750      KVR    AP  PM
12  350  SIRISHA    TS  HR

In [11]:
gby.count()

       CID  CNAME  DSG
STATE
AP       7      7    7
BANG     2      2    2
DELHI    3      3    3
TS       5      5    5

In [13]:
gby.get_group("AP")

    CID      CNAME STATE DSG
1   200   SAGATIKA    AP  SE
3   400     ROSSUM    AP  TL
6   700  TEJASWANI    AP  SE
9   750        KVR    AP  PM
11  550    MOUNIKA    AP  PM
13  150    MADHVAI    AP  HR
15  950     ANJALI    AP  HR

In [14]:
gby.get_group("AP").count()

CID      7
CNAME    7
STATE    7
DSG      7
dtype: int64

In [16]:
gby.get_group("AP").count().size

4

In [17]:
gby.get_group("AP").count().unique()

array([7])

In [18]:
gby.get_group("AP")["CNAME"]

1      SAGATIKA
3        ROSSUM
6     TEJASWANI
9           KVR
11      MOUNIKA
13      MADHVAI
15       ANJALI
Name: CNAME, dtype: object

In [19]:
df.groupby("STATE").size()

STATE
AP       7
BANG     2
DELHI    3
TS       5
dtype: int64

In [20]:
df.groupby("STATE").get_group("AP")

    CID      CNAME STATE DSG
1   200   SAGATIKA    AP  SE
3   400     ROSSUM    AP  TL
6   700  TEJASWANI    AP  SE
9   750        KVR    AP  PM
11  550    MOUNIKA    AP  PM
13  150    MADHVAI    AP  HR
15  950     ANJALI    AP  HR

In [21]:
lst=[[11,"Jack",44,"Sydney",19],[12,"Rita",41,"Delhi",17],[13,"Aadi",46,"Mumbai",11],
    [14,"Mothi",45,"Delhi",15],[15,"Veena",43,"Delhi",14],[16,"Shaunak",42,"Mumbai",17],
    [17,"Manik",42,"Sydney",14],[18,"Vikas",42,"Delhi",11],[19,"Samir",42,"Mumbai",15],
    [20,"Shobit",40,"Sydney",12]]
df=pd.DataFrame(lst)
print(df)

    0        1   2       3   4
0  11     Jack  44  Sydney  19
1  12     Rita  41   Delhi  17
2  13     Aadi  46  Mumbai  11
3  14    Mothi  45   Delhi  15
4  15    Veena  43   Delhi  14
5  16  Shaunak  42  Mumbai  17
6  17    Manik  42  Sydney  14
7  18    Vikas  42   Delhi  11
8  19    Samir  42  Mumbai  15
9  20   Shobit  40  Sydney  12

In [22]:
lst=[[11,"Jack",44,"Sydney",19],[12,"Rita",41,"Delhi",17],[13,"Aadi",46,"Mumbai",11],
    [14,"Mothi",45,"Delhi",15],[15,"Veena",43,"Delhi",14],[16,"Shaunak",42,"Mumbai",17],
    [17,"Manik",42,"Sydney",14],[18,"Vikas",42,"Delhi",11],[19,"Samir",42,"Mumbai",15],
    [20,"Shobit",40,"Sydney",12]]
df=pd.DataFrame(lst,columns=["CID","NAME","AGE","CITY",'EXPR'])
print(df)

   CID     NAME  AGE    CITY  EXPR
0   11     Jack   44  Sydney    19
1   12     Rita   41   Delhi    17
2   13     Aadi   46  Mumbai    11
3   14    Mothi   45   Delhi    15
4   15    Veena   43   Delhi    14
5   16  Shaunak   42  Mumbai    17
6   17    Manik   42  Sydney    14
7   18    Vikas   42   Delhi    11
8   19    Samir   42  Mumbai    15
9   20   Shobit   40  Sydney    12

In [23]:
for gn,gnifo in df.groupby("CITY"):
    print("City Name:{}".format(gn))
    print("Group INfo")
    print(gninfo)
    print("=========================================")

City Name:Delhi
Group INfo
    CID    CNAME STATE DSG
0   100    SUSMA    TS  SE
2   300    LAXMI    TS  TL
7   800   FAZINA    TS  PM
12  350  SIRISHA    TS  HR
16  250    KOMAL    TS  TL
=========================================
City Name:Mumbai
Group INfo
    CID    CNAME STATE DSG
0   100    SUSMA    TS  SE
2   300    LAXMI    TS  TL
7   800   FAZINA    TS  PM
12  350  SIRISHA    TS  HR
16  250    KOMAL    TS  TL
=========================================
City Name:Sydney
Group INfo
    CID    CNAME STATE DSG
0   100    SUSMA    TS  SE
2   300    LAXMI    TS  TL
7   800   FAZINA    TS  PM
12  350  SIRISHA    TS  HR
16  250    KOMAL    TS  TL
=========================================

In [24]:
# Get the first group
df.groupby("CITY").first()

        CID  NAME  AGE  EXPR
CITY
Delhi    12  Rita   41    17
Mumbai   13  Aadi   46    11
Sydney   11  Jack   44    19

In [28]:
# Get the first group Name
df.groupby("CITY").first()[["NAME"]]

        NAME
CITY
Delhi   Rita
Mumbai  Aadi
Sydney  Jack

In [29]:
# Get the first group Name and AGE
df.groupby("CITY").first()[["NAME","AGE"]]

        NAME  AGE
CITY
Delhi   Rita   41
Mumbai  Aadi   46
Sydney  Jack   44

In [30]:
# Get the city group size
df.groupby("CITY").size()

CITY
Delhi     4
Mumbai    3
Sydney    3
dtype: int64

In [36]:
# Get the mean of age group 
values=df.groupby("CITY").agg({'AGE':'mean',"EXPR":"mean"})
print(values)

              AGE       EXPR
CITY
Delhi   42.750000  14.250000
Mumbai  43.333333  14.333333
Sydney  42.000000  15.000000

In [35]:
# Get the mean and sumof age group 
values=df.groupby("CITY").agg({'AGE':'mean',"EXPR":"sum"})
print(values)

              AGE  EXPR
CITY
Delhi   42.750000    57
Mumbai  43.333333    43
Sydney  42.000000    45

In [37]:
# Get the mean of age group 
values=df.groupby("CITY")["AGE"].agg({'size','mean',"sum"})
print(values)

        size       mean  sum
CITY
Delhi      4  42.750000  171
Mumbai     3  43.333333  130
Sydney     3  42.000000  126

In [38]:
# Get the mean of age group 
values=df.groupby("CITY")["AGE"].agg({'size','mean',"sum",'median',"std"})
print(values)

        size       mean  median       std  sum
CITY
Delhi      4  42.750000    42.5  1.707825  171
Mumbai     3  43.333333    42.0  2.309401  130
Sydney     3  42.000000    42.0  2.000000  126

In [39]:
# Get the mean of age group 
values=df.groupby("CITY")["AGE"].agg({'size','mean',"sum",'median',"std",'var'})
print(values)

        size       var       mean  median       std  sum
CITY
Delhi      4  2.916667  42.750000    42.5  1.707825  171
Mumbai     3  5.333333  43.333333    42.0  2.309401  130
Sydney     3  4.000000  42.000000    42.0  2.000000  126