In [2]:
import pandas as pd
df=pd.read_csv("D:\\Akash\\Python\\KVR-PYTHON-PART-1\\PANDAS\\NOTES\\peoples.csv")
print(df)

    CID      CNAME  STATE DSG
0   100      SUSMA     TS  SE
1   200   SAGATIKA     AP  SE
2   300      LAXMI     TS  TL
3   400     ROSSUM     AP  TL
4   500     NARESH  DELHI  PM
5   600      VINAY  DELHI   M
6   700  TEJASWANI     AP  SE
7   800     FAZINA     TS  PM
8   900    SANSKAR  DELHI  SE
9   750        KVR     AP  PM
10  650      RADHA   BANG  TL
11  550    MOUNIKA     AP  PM
12  350    SIRISHA     TS  HR
13  150    MADHVAI     AP  HR
14  450   JAYSHREE   BANG  HR
15  950     ANJALI     AP  HR
16  250      KOMAL     TS  TL

In [3]:
len(df)

17

In [5]:
df.loc[len(df)]=[125,'Anjali',"AP",'DA']

In [6]:
print(df)

    CID      CNAME  STATE DSG
0   100      SUSMA     TS  SE
1   200   SAGATIKA     AP  SE
2   300      LAXMI     TS  TL
3   400     ROSSUM     AP  TL
4   500     NARESH  DELHI  PM
5   600      VINAY  DELHI   M
6   700  TEJASWANI     AP  SE
7   800     FAZINA     TS  PM
8   900    SANSKAR  DELHI  SE
9   750        KVR     AP  PM
10  650      RADHA   BANG  TL
11  550    MOUNIKA     AP  PM
12  350    SIRISHA     TS  HR
13  150    MADHVAI     AP  HR
14  450   JAYSHREE   BANG  HR
15  950     ANJALI     AP  HR
16  250      KOMAL     TS  TL
17  125     Anjali     AP  DA

In [7]:
df.loc[len(df)]=[135,'Priya',"TS",'DA']

In [8]:
print(df)

    CID      CNAME  STATE DSG
0   100      SUSMA     TS  SE
1   200   SAGATIKA     AP  SE
2   300      LAXMI     TS  TL
3   400     ROSSUM     AP  TL
4   500     NARESH  DELHI  PM
5   600      VINAY  DELHI   M
6   700  TEJASWANI     AP  SE
7   800     FAZINA     TS  PM
8   900    SANSKAR  DELHI  SE
9   750        KVR     AP  PM
10  650      RADHA   BANG  TL
11  550    MOUNIKA     AP  PM
12  350    SIRISHA     TS  HR
13  150    MADHVAI     AP  HR
14  450   JAYSHREE   BANG  HR
15  950     ANJALI     AP  HR
16  250      KOMAL     TS  TL
17  125     Anjali     AP  DA
18  135      Priya     TS  DA

In [9]:
df.sort_values(["CID"])

    CID      CNAME  STATE DSG
0   100      SUSMA     TS  SE
17  125     Anjali     AP  DA
18  135      Priya     TS  DA
13  150    MADHVAI     AP  HR
1   200   SAGATIKA     AP  SE
16  250      KOMAL     TS  TL
2   300      LAXMI     TS  TL
12  350    SIRISHA     TS  HR
3   400     ROSSUM     AP  TL
14  450   JAYSHREE   BANG  HR
4   500     NARESH  DELHI  PM
11  550    MOUNIKA     AP  PM
5   600      VINAY  DELHI   M
10  650      RADHA   BANG  TL
6   700  TEJASWANI     AP  SE
9   750        KVR     AP  PM
7   800     FAZINA     TS  PM
8   900    SANSKAR  DELHI  SE
15  950     ANJALI     AP  HR

In [12]:
df.sort_values(["CNAME"])

    CID      CNAME  STATE DSG
15  950     ANJALI     AP  HR
17  125     Anjali     AP  DA
7   800     FAZINA     TS  PM
14  450   JAYSHREE   BANG  HR
16  250      KOMAL     TS  TL
9   750        KVR     AP  PM
2   300      LAXMI     TS  TL
13  150    MADHVAI     AP  HR
11  550    MOUNIKA     AP  PM
4   500     NARESH  DELHI  PM
18  135      Priya     TS  DA
10  650      RADHA   BANG  TL
3   400     ROSSUM     AP  TL
1   200   SAGATIKA     AP  SE
8   900    SANSKAR  DELHI  SE
12  350    SIRISHA     TS  HR
0   100      SUSMA     TS  SE
6   700  TEJASWANI     AP  SE
5   600      VINAY  DELHI   M