In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("D:\\Akash\\Python\\KVR-PYTHON-PART-1\\PANDAS\\googleplaystore.csv")
print(df)

                                                     App             Category  \
0         Photo Editor & Candy Camera & Grid & ScrapBook       ART_AND_DESIGN
1                                    Coloring book moana       ART_AND_DESIGN
2      U Launcher Lite – FREE Live Cool Themes, Hide ...       ART_AND_DESIGN
3                                  Sketch - Draw & Paint       ART_AND_DESIGN
4                  Pixel Draw - Number Art Coloring Book       ART_AND_DESIGN
...                                                  ...                  ...
10836                                   Sya9a Maroc - FR               FAMILY
10837                   Fr. Mike Schmitz Audio Teachings               FAMILY
10838                             Parkinson Exercices FR              MEDICAL
10839                      The SCP Foundation DB fr nn5n  BOOKS_AND_REFERENCE
10840      iHoroscope - 2018 Daily Horoscope & Astrology            LIFESTYLE

       Rating Reviews                Size     Installs  Type Price  \
0         4.1     159                 19M      10,000+  Free     0
1         3.9     967                 14M     500,000+  Free     0
2         4.7   87510                8.7M   5,000,000+  Free     0
3         4.5  215644                 25M  50,000,000+  Free     0
4         4.3     967                2.8M     100,000+  Free     0
...       ...     ...                 ...          ...   ...   ...
10836     4.5      38                 53M       5,000+  Free     0
10837     5.0       4                3.6M         100+  Free     0
10838     NaN       3                9.5M       1,000+  Free     0
10839     4.5     114  Varies with device       1,000+  Free     0
10840     4.5  398307                 19M  10,000,000+  Free     0

      Content Rating                     Genres      Last Updated  \
0           Everyone               Art & Design   January 7, 2018
1           Everyone  Art & Design;Pretend Play  January 15, 2018
2           Everyone               Art & Design    August 1, 2018
3               Teen               Art & Design      June 8, 2018
4           Everyone    Art & Design;Creativity     June 20, 2018
...              ...                        ...               ...
10836       Everyone                  Education     July 25, 2017
10837       Everyone                  Education      July 6, 2018
10838       Everyone                    Medical  January 20, 2017
10839     Mature 17+          Books & Reference  January 19, 2015
10840       Everyone                  Lifestyle     July 25, 2018

              Current Ver         Android Ver
0                   1.0.0        4.0.3 and up
1                   2.0.0        4.0.3 and up
2                   1.2.4        4.0.3 and up
3      Varies with device          4.2 and up
4                     1.1          4.4 and up
...                   ...                 ...
10836                1.48          4.1 and up
10837                 1.0          4.1 and up
10838                 1.0          2.2 and up
10839  Varies with device  Varies with device
10840  Varies with device  Varies with device

[10841 rows x 13 columns]

In [4]:
pd.set_option("display.max_columns",None)
df=pd.read_csv("D:\\Akash\\Python\\KVR-PYTHON-PART-1\\PANDAS\\googleplaystore.csv")
print(df)

                                                     App             Category  \
0         Photo Editor & Candy Camera & Grid & ScrapBook       ART_AND_DESIGN
1                                    Coloring book moana       ART_AND_DESIGN
2      U Launcher Lite – FREE Live Cool Themes, Hide ...       ART_AND_DESIGN
3                                  Sketch - Draw & Paint       ART_AND_DESIGN
4                  Pixel Draw - Number Art Coloring Book       ART_AND_DESIGN
...                                                  ...                  ...
10836                                   Sya9a Maroc - FR               FAMILY
10837                   Fr. Mike Schmitz Audio Teachings               FAMILY
10838                             Parkinson Exercices FR              MEDICAL
10839                      The SCP Foundation DB fr nn5n  BOOKS_AND_REFERENCE
10840      iHoroscope - 2018 Daily Horoscope & Astrology            LIFESTYLE

       Rating Reviews                Size     Installs  Type Price  \
0         4.1     159                 19M      10,000+  Free     0
1         3.9     967                 14M     500,000+  Free     0
2         4.7   87510                8.7M   5,000,000+  Free     0
3         4.5  215644                 25M  50,000,000+  Free     0
4         4.3     967                2.8M     100,000+  Free     0
...       ...     ...                 ...          ...   ...   ...
10836     4.5      38                 53M       5,000+  Free     0
10837     5.0       4                3.6M         100+  Free     0
10838     NaN       3                9.5M       1,000+  Free     0
10839     4.5     114  Varies with device       1,000+  Free     0
10840     4.5  398307                 19M  10,000,000+  Free     0

      Content Rating                     Genres      Last Updated  \
0           Everyone               Art & Design   January 7, 2018
1           Everyone  Art & Design;Pretend Play  January 15, 2018
2           Everyone               Art & Design    August 1, 2018
3               Teen               Art & Design      June 8, 2018
4           Everyone    Art & Design;Creativity     June 20, 2018
...              ...                        ...               ...
10836       Everyone                  Education     July 25, 2017
10837       Everyone                  Education      July 6, 2018
10838       Everyone                    Medical  January 20, 2017
10839     Mature 17+          Books & Reference  January 19, 2015
10840       Everyone                  Lifestyle     July 25, 2018

              Current Ver         Android Ver
0                   1.0.0        4.0.3 and up
1                   2.0.0        4.0.3 and up
2                   1.2.4        4.0.3 and up
3      Varies with device          4.2 and up
4                     1.1          4.4 and up
...                   ...                 ...
10836                1.48          4.1 and up
10837                 1.0          4.1 and up
10838                 1.0          2.2 and up
10839  Varies with device  Varies with device
10840  Varies with device  Varies with device

[10841 rows x 13 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  object
 1   Category        10841 non-null  object
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  object
 4   Size            10841 non-null  object
 5   Installs        10841 non-null  object
 6   Type            10840 non-null  object
 7   Price           10841 non-null  object
 8   Content Rating  10840 non-null  object
 9   Genres          10841 non-null  object
 10  Last Updated    10841 non-null  object
 11  Current Ver     10833 non-null  object
 12  Android Ver     10838 non-null  object
dtypes: float64(1), object(12)
memory usage: 1.1+ MB

In [6]:
# 1 Display First five Row
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [7]:
# 1 Display First 3 Row
df.head(3)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up

In [10]:
# 2 Display last five Row
df.tail()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [11]:
# 2 Display last 3 Row
df.tail(3)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [12]:
# 3 Find Shape of Our DataSate (Number of Rows and Number of columns)
df.shape

(10841, 13)

In [13]:
# 3 Find Shape of Our DataSate (Number of Rows and Number of columns)
df.shape
print("Number of Apps =",df.shape[0])
print("Number of columns in each app=",df.shape[1])

Number of Apps = 10841
Number of columns in each app= 13

In [14]:
# Display the Column Name the all the apps
df.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='object')

In [15]:
for i in df.columns:
    print(i)

App
Category
Rating
Reviews
Size
Installs
Type
Price
Content Rating
Genres
Last Updated
Current Ver
Android Ver

In [16]:
# 4 Get information about our DataSet 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  object
 1   Category        10841 non-null  object
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  object
 4   Size            10841 non-null  object
 5   Installs        10841 non-null  object
 6   Type            10840 non-null  object
 7   Price           10841 non-null  object
 8   Content Rating  10840 non-null  object
 9   Genres          10841 non-null  object
 10  Last Updated    10841 non-null  object
 11  Current Ver     10833 non-null  object
 12  Android Ver     10838 non-null  object
dtypes: float64(1), object(12)
memory usage: 1.1+ MB

In [18]:
# 5 Get Overall Statistics About THe DataFrame
df.describe()

            Rating
count  9367.000000
mean      4.193338
std       0.537431
min       1.000000
25%       4.000000
50%       4.300000
75%       4.500000
max      19.000000

In [20]:
# 5 Get Overall Statistics About THe DataFrame
df.describe(include='all') # Give Descriptive Statical Information of al Columns

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
count,10841,10841,9367.000000,10841,10841,10841,10840,10841,10840,10841,10841,10833,10838
unique,9660,34,NaN,6002,462,22,3,93,6,120,1378,2832,33
top,ROBLOX,FAMILY,NaN,0,Varies with device,"1,000,000+",Free,0,Everyone,Tools,"August 3, 2018",Varies with device,4.1 and up
freq,9,1972,NaN,596,1695,1579,10039,10040,8714,842,326,1459,2451
mean,NaN,NaN,4.193338,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,0.537431,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,4.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,4.300000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,4.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,19.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
# 6 Total No. of Astrology app 
df.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='object')

In [25]:
df["App"]

0           Photo Editor & Candy Camera & Grid & ScrapBook
1                                      Coloring book moana
2        U Launcher Lite – FREE Live Cool Themes, Hide ...
3                                    Sketch - Draw & Paint
4                    Pixel Draw - Number Art Coloring Book
                               ...
10836                                     Sya9a Maroc - FR
10837                     Fr. Mike Schmitz Audio Teachings
10838                               Parkinson Exercices FR
10839                        The SCP Foundation DB fr nn5n
10840        iHoroscope - 2018 Daily Horoscope & Astrology
Name: App, Length: 10841, dtype: object

In [28]:
df.loc[df["App"]=='Astrology']

Empty DataFrame
Columns: [App, Category, Rating, Reviews, Size, Installs, Type, Price, Content Rating, Genres, Last Updated, Current Ver, Android Ver]
Index: []

In [29]:
df["App"].str.contains('Astrology')

0        False
1        False
2        False
3        False
4        False
         ...
10836    False
10837    False
10838    False
10839    False
10840     True
Name: App, Length: 10841, dtype: bool

In [32]:
df[df["App"].str.contains('Astrology')]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
1570,Horoscopes – Daily Zodiac Horoscope and Astrology,LIFESTYLE,4.6,161143,11M,"10,000,000+",Free,0,Everyone 10+,Lifestyle,"June 25, 2018",5.2.4(881),4.0.3 and up
1592,သိင်္ Astrology - Min Thein Kha BayDin,LIFESTYLE,4.7,2225,15M,"100,000+",Free,0,Everyone,Lifestyle,"July 26, 2018",4.2.1,4.0.3 and up
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [35]:
df[df["App"].str.contains('Astrology',case=False)]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
1570,Horoscopes – Daily Zodiac Horoscope and Astrology,LIFESTYLE,4.6,161143,11M,"10,000,000+",Free,0,Everyone 10+,Lifestyle,"June 25, 2018",5.2.4(881),4.0.3 and up
1592,သိင်္ Astrology - Min Thein Kha BayDin,LIFESTYLE,4.7,2225,15M,"100,000+",Free,0,Everyone,Lifestyle,"July 26, 2018",4.2.1,4.0.3 and up
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [36]:
x=len(df[df["App"].str.contains('Astrology',case=False)])
print("Number Of Apps Contains a word Astrology =",x)

Number Of Apps Contains a word Astrology = 3

In [37]:
# 7 Find Average App Rating
df.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='object')

In [38]:
df['Rating']

0        4.1
1        3.9
2        4.7
3        4.5
4        4.3
        ...
10836    4.5
10837    5.0
10838    NaN
10839    4.5
10840    4.5
Name: Rating, Length: 10841, dtype: float64

In [40]:
avr=df['Rating'].mean()
print("Average App Rating Google Play Store=",avr)

Average App Rating Google Play Store= 4.193338315362443

In [43]:
# 8 Find The Unique Category
df['Category']

0             ART_AND_DESIGN
1             ART_AND_DESIGN
2             ART_AND_DESIGN
3             ART_AND_DESIGN
4             ART_AND_DESIGN
                ...
10836                 FAMILY
10837                 FAMILY
10838                MEDICAL
10839    BOOKS_AND_REFERENCE
10840              LIFESTYLE
Name: Category, Length: 10841, dtype: object

In [45]:
# 8 Find The Unique Category
print("Total No. of Unique Category",df['Category'].nunique())

Total No. of Unique Category 34

In [54]:
# 9 Find Whic Category Higest getting Average Ratting
#    1Group the Category
for gn, gninfo in df.groupby('Category'):
    print("Group Name :",gn)
    print("Group Info :\n",gninfo)

Group Name : 1.9
Group Info :
                                            App Category  Rating Reviews  \
10472  Life Made WI-Fi Touchscreen Photo Frame      1.9    19.0    3.0M

         Size Installs Type     Price Content Rating             Genres  \
10472  1,000+     Free    0  Everyone            NaN  February 11, 2018

      Last Updated Current Ver Android Ver
10472       1.0.19  4.0 and up         NaN
Group Name : ART_AND_DESIGN
Group Info :
                                                     App        Category  \
0        Photo Editor & Candy Camera & Grid & ScrapBook  ART_AND_DESIGN
1                                   Coloring book moana  ART_AND_DESIGN
2     U Launcher Lite – FREE Live Cool Themes, Hide ...  ART_AND_DESIGN
3                                 Sketch - Draw & Paint  ART_AND_DESIGN
4                 Pixel Draw - Number Art Coloring Book  ART_AND_DESIGN
...                                                 ...             ...
7174                            Easy DIY CD Craft Ideas  ART_AND_DESIGN
8679                                       Dp for girls  ART_AND_DESIGN
8712             Name Art DP - Focus n Filter Text 2018  ART_AND_DESIGN
8871                             Test Application DT 02  ART_AND_DESIGN
8888            Spring flowers theme couleurs d t space  ART_AND_DESIGN

      Rating Reviews  Size     Installs  Type Price Content Rating  \
0        4.1     159   19M      10,000+  Free     0       Everyone
1        3.9     967   14M     500,000+  Free     0       Everyone
2        4.7   87510  8.7M   5,000,000+  Free     0       Everyone
3        4.5  215644   25M  50,000,000+  Free     0           Teen
4        4.3     967  2.8M     100,000+  Free     0       Everyone
...      ...     ...   ...          ...   ...   ...            ...
7174     NaN       7  5.6M       5,000+  Free     0       Everyone
8679     4.2     175  8.2M      50,000+  Free     0       Everyone
8712     4.3     132  7.7M      10,000+  Free     0       Everyone
8871     NaN       0  1.2M           0+  Free     0       Everyone
8888     5.0       1  2.9M         100+  Free     0       Everyone

                         Genres      Last Updated         Current Ver  \
0                  Art & Design   January 7, 2018               1.0.0
1     Art & Design;Pretend Play  January 15, 2018               2.0.0
2                  Art & Design    August 1, 2018               1.2.4
3                  Art & Design      June 8, 2018  Varies with device
4       Art & Design;Creativity     June 20, 2018                 1.1
...                         ...               ...                 ...
7174               Art & Design      May 30, 2018                 1.0
8679               Art & Design      May 26, 2017                 1.2
8712               Art & Design   January 4, 2018                   1
8871               Art & Design    March 14, 2017                 4.0
8888               Art & Design    April 18, 2018               1.0.2

       Android Ver
0     4.0.3 and up
1     4.0.3 and up
2     4.0.3 and up
3       4.2 and up
4       4.4 and up
...            ...
7174    2.3 and up
8679  4.0.3 and up
8712    4.1 and up
8871    4.2 and up
8888    4.0 and up

[65 rows x 13 columns]
Group Name : AUTO_AND_VEHICLES
Group Info :
                                    App           Category  Rating Reviews  \
49         Monster Truck Stunt 3D 2019  AUTO_AND_VEHICLES     4.2     367
50                Real Tractor Farming  AUTO_AND_VEHICLES     4.0    1598
51     Ultimate F1 Racing Championship  AUTO_AND_VEHICLES     3.8     284
52       Used Cars and Trucks for Sale  AUTO_AND_VEHICLES     4.6   17057
53            American Muscle Car Race  AUTO_AND_VEHICLES     3.9     129
...                                ...                ...     ...     ...
10137         EZ-ELD Driver App (Free)  AUTO_AND_VEHICLES     2.1      83
10345          Repair Hyundai Santa Fe  AUTO_AND_VEHICLES     3.9      22
10486    FJ Drive: Mercedes-Benz Lease  AUTO_AND_VEHICLES     4.6     107
10764                FP Transportation  AUTO_AND_VEHICLES     NaN       1
10811                      FR Plus 1.6  AUTO_AND_VEHICLES     NaN       4

                     Size    Installs  Type Price Content Rating  \
49                    25M    100,000+  Free     0       Everyone
50                    56M  1,000,000+  Free     0       Everyone
51                    57M    100,000+  Free     0       Everyone
52     Varies with device  1,000,000+  Free     0       Everyone
53                    35M    100,000+  Free     0       Everyone
...                   ...         ...   ...   ...            ...
10137                4.8M      5,000+  Free     0       Everyone
10345                 97M      1,000+  Free     0       Everyone
10486                 27M     10,000+  Free     0       Everyone
10764                885k          1+  Free     0       Everyone
10811                3.9M        100+  Free     0       Everyone

                Genres      Last Updated         Current Ver  \
49     Auto & Vehicles      May 10, 2018                 1.0
50     Auto & Vehicles     July 26, 2018                11.0
51     Auto & Vehicles     July 26, 2018                 3.0
52     Auto & Vehicles     July 30, 2018  Varies with device
53     Auto & Vehicles     July 26, 2018                 3.0
...                ...               ...                 ...
10137  Auto & Vehicles     July 29, 2018              1.0.12
10345  Auto & Vehicles  January 31, 2018                 1.0
10486  Auto & Vehicles  November 6, 2017               2.0.0
10764  Auto & Vehicles     March 9, 2018              10.0.0
10811  Auto & Vehicles     July 24, 2018               1.3.6

              Android Ver
49           4.0.3 and up
50             4.1 and up
51             4.1 and up
52     Varies with device
53             4.1 and up
...                   ...
10137          4.3 and up
10345          4.0 and up
10486          4.1 and up
10764          4.0 and up
10811         4.4W and up

[85 rows x 13 columns]
Group Name : BEAUTY
Group Info :
                                                      App Category  Rating  \
98                            Hush - Beauty for Everyone   BEAUTY     4.7
99                        ipsy: Makeup, Beauty, and Tips   BEAUTY     4.9
100                      Natural recipes for your beauty   BEAUTY     4.7
101    BestCam Selfie-selfie, beauty camera, photo ed...   BEAUTY     3.9
102                           Mirror - Zoom & Exposure -   BEAUTY     3.9
103                                 Beauty Selfie Camera   BEAUTY     4.2
104                              Hairstyles step by step   BEAUTY     4.6
105                                   Filters for Selfie   BEAUTY     4.3
106                                Tie - Always be happy   BEAUTY     4.7
107                                          Ulta Beauty   BEAUTY     4.7
108                                 Prom MakeUp Tutorial   BEAUTY     4.8
109                                        Selfie Camera   BEAUTY     4.2
110                           Sweet Selfie Beauty Camera   BEAUTY     4.3
111                              Colors of white in Urdu   BEAUTY     4.5
112        Selfie Camera Photo Editor & Filter & Sticker   BEAUTY     4.1
113                            Wrinkles and rejuvenation   BEAUTY     NaN
114                              Eyes Makeup Beauty Tips   BEAUTY     4.2
115                                    Photo Editor 2018   BEAUTY     4.5
116                    Step By Step Eyes Makeup Tutorial   BEAUTY     4.4
117                        Beauty Camera - Selfie Camera   BEAUTY     4.0
118                                     Girls Hairstyles   BEAUTY     4.1
119               Mirror Camera (Mirror + Selfie Camera)   BEAUTY     4.1
120                 Beauty Tips - Beauty Tips in Sinhala   BEAUTY     4.4
121                     Haircut Tutorials/Haircut Videos   BEAUTY     4.6
122    Sephora: Skin Care, Beauty Makeup & Fragrance ...   BEAUTY     4.5
123                               Manicure - nail design   BEAUTY     NaN
124       Sticker Camera - Selfie Filters, Beauty Camera   BEAUTY     3.9
125                                   Filters for B Live   BEAUTY     4.4
126                         Skin Care and Natural Beauty   BEAUTY     NaN
127                             Facial Wrinkle Reduction   BEAUTY     4.6
128                                        Makeup Videos   BEAUTY     3.8
129                  Secrets of beauty, youth and health   BEAUTY     NaN
130                   Recipes and tips for losing weight   BEAUTY     NaN
131                                       Discover Color   BEAUTY     4.0
132                           Eyeliner step by step 2018   BEAUTY     4.3
133                       Dresses Ideas & Fashions +3000   BEAUTY     4.5
134                        Lady adviser (beauty, health)   BEAUTY     NaN
135                    Step By Step Hairstyles For Women   BEAUTY     4.1
136                                       Rainbow Camera   BEAUTY     3.7
137                           Methods of teeth whitening   BEAUTY     4.7
138                                Girls hairstyles 2018   BEAUTY     4.2
5192        AI Face Beauty Analysis - IntelliFace (Free)   BEAUTY     3.1
5998                                  Aura Hair Group BC   BEAUTY     NaN
6222                                        BH Cosmetics   BEAUTY     4.0
6318                           BJ Grand Salon Mobile App   BEAUTY     NaN
6506                              BN Whitening Shoppe Ph   BEAUTY     4.0
6828                                     BU Beauty Rooms   BEAUTY     NaN
7021                        Best Hairstyles step by step   BEAUTY     4.5
7460                         Calvin Klein Petite Dresses   BEAUTY     NaN
8505                                DK Studio Barbershop   BEAUTY     NaN
9205                                        Skin Disease   BEAUTY     4.0
10022                     Beard Live Camera Photo Editor   BEAUTY     4.7
10289                                       Female Daily   BEAUTY     3.9

      Reviews                Size     Installs  Type Price Content Rating  \
98      18900                 17M     500,000+  Free     0       Everyone
99      49790                 14M   1,000,000+  Free     0       Everyone
100      1150                9.8M     100,000+  Free     0       Everyone
101      1739                 21M     500,000+  Free     0       Everyone
102     32090  Varies with device   1,000,000+  Free     0       Everyone
103      2225                 52M     500,000+  Free     0       Everyone
104      4369                 14M     100,000+  Free     0       Everyone
105      8572                 25M   1,000,000+  Free     0       Everyone
106       964                9.0M      50,000+  Free     0       Everyone
107     42050  Varies with device   1,000,000+  Free     0       Everyone
108       104                 12M      10,000+  Free     0       Everyone
109     17934  Varies with device   1,000,000+  Free     0       Everyone
110       601                 35M     100,000+  Free     0       Everyone
111        36                6.7M      10,000+  Free     0       Everyone
112       187                 30M      50,000+  Free     0           Teen
113       182                5.7M     100,000+  Free     0   Everyone 10+
114        30                2.9M      10,000+  Free     0       Everyone
115       134                 17M      10,000+  Free     0       Everyone
116        74                2.9M      10,000+  Free     0       Everyone
117    113715  Varies with device  10,000,000+  Free     0       Everyone
118      3595  Varies with device     500,000+  Free     0       Everyone
119      9315                2.6M   1,000,000+  Free     0       Everyone
120        75                4.2M      50,000+  Free     0       Everyone
121        38                7.1M      10,000+  Free     0       Everyone
122     26834                 57M   1,000,000+  Free     0       Everyone
123       119                3.7M      50,000+  Free     0       Everyone
124      2277                 22M     500,000+  Free     0       Everyone
125      2280                 24M     500,000+  Free     0       Everyone
126       654                7.4M     100,000+  Free     0           Teen
127       184                 21M      10,000+  Free     0       Everyone
128         9                3.4M       5,000+  Free     0       Everyone
129        77                2.9M      10,000+  Free     0     Mature 17+
130        35                3.1M      10,000+  Free     0   Everyone 10+
131       364                6.4M     100,000+  Free     0       Everyone
132        18                3.2M       5,000+  Free     0       Everyone
133       473                8.2M     100,000+  Free     0     Mature 17+
134        30                9.9M      10,000+  Free     0     Mature 17+
135        66                2.9M      10,000+  Free     0       Everyone
136      3871                 23M   1,000,000+  Free     0       Everyone
137       257                4.6M      50,000+  Free     0       Everyone
138        62                3.1M      10,000+  Free     0       Everyone
5192       40                 13M      10,000+  Free     0       Everyone
5998        0  Varies with device         100+  Free     0       Everyone
6222        2                3.6M       1,000+  Free     0       Everyone
6318        1                 15M         100+  Free     0       Everyone
6506        2                 13M         100+  Free     0       Everyone
6828        1                6.0M          50+  Free     0       Everyone
7021    45452                9.2M   5,000,000+  Free     0       Everyone
7460        0                3.7M         500+  Free     0       Everyone
8505        8                 17M         100+  Free     0       Everyone
9205        1                2.2M         100+  Free     0       Everyone
10022     900                 30M       5,000+  Free     0       Everyone
10289    4354                 42M     100,000+  Free     0           Teen

       Genres        Last Updated         Current Ver         Android Ver
98     Beauty      August 2, 2018              6.10.1          5.0 and up
99     Beauty    November 9, 2017               2.3.0          4.1 and up
100    Beauty        May 15, 2018                 4.0          4.1 and up
101    Beauty       July 12, 2018               1.0.6        4.0.3 and up
102    Beauty    October 24, 2016  Varies with device  Varies with device
103    Beauty   February 28, 2018                 1.6          4.1 and up
104    Beauty       July 25, 2018                 1.9        4.0.3 and up
105    Beauty        May 10, 2018               1.1.0          4.0 and up
106    Beauty       June 21, 2018                 4.0          4.2 and up
107    Beauty        June 5, 2018                 5.4          5.0 and up
108    Beauty       June 26, 2018                 1.3        4.0.3 and up
109    Beauty  September 12, 2017  Varies with device  Varies with device
110    Beauty        June 2, 2018               2.0.0          4.0 and up
111    Beauty       July 26, 2018                 6.0          4.0 and up
112    Beauty       July 24, 2018               3.0.1        4.0.3 and up
113    Beauty  September 20, 2017                 8.0          3.0 and up
114    Beauty       April 9, 2018               3.3.9        4.0.3 and up
115    Beauty       March 1, 2018                1.20        4.0.3 and up
116    Beauty       April 5, 2018              2.3.09        4.0.3 and up
117    Beauty      August 3, 2017  Varies with device  Varies with device
118    Beauty        May 24, 2018  Varies with device          4.0 and up
119    Beauty   November 21, 2017               1.4.2          4.0 and up
120    Beauty    October 18, 2017               1.0.0        4.0.3 and up
121    Beauty        May 29, 2018                 1.0          4.0 and up
122    Beauty       July 24, 2018                18.5          5.0 and up
123    Beauty       July 23, 2018                 1.3          4.1 and up
124    Beauty       July 12, 2018               1.1.0        4.0.3 and up
125    Beauty        May 14, 2018               1.1.0          4.0 and up
126    Beauty       July 17, 2018                1.15          4.1 and up
127    Beauty        July 2, 2018                 1.5          4.1 and up
128    Beauty        June 7, 2018                 1.0          4.0 and up
129    Beauty      August 8, 2017                 2.0          2.3 and up
130    Beauty   December 11, 2017                 2.0          3.0 and up
131    Beauty        May 24, 2018                 1.1        4.0.3 and up
132    Beauty        June 1, 2018              1.2.13        4.0.3 and up
133    Beauty       March 1, 2017             1.0.2.0          1.6 and up
134    Beauty    January 24, 2018                 3.0          3.0 and up
135    Beauty       April 5, 2018              3.1.89        4.0.3 and up
136    Beauty       July 30, 2018               2.2.0          4.0 and up
137    Beauty      August 7, 2017                 1.0        4.0.3 and up
138    Beauty        May 28, 2018               1.9.2        4.0.3 and up
5192   Beauty      April 11, 2018                  20          4.1 and up
5998   Beauty      April 23, 2018  Varies with device        4.0.3 and up
6222   Beauty        May 29, 2018                 1.0          4.0 and up
6318   Beauty       June 14, 2018               1.0.7          5.0 and up
6506   Beauty       March 6, 2018               1.0.8        4.0.3 and up
6828   Beauty   February 17, 2017                 1.0          4.4 and up
7021   Beauty       July 19, 2018                1.25          4.0 and up
7460   Beauty      March 23, 2018                   1          4.1 and up
8505   Beauty      March 20, 2018                 1.1          4.1 and up
9205   Beauty     August 30, 2017                 1.0          2.2 and up
10022  Beauty      March 25, 2018                 1.1        4.0.3 and up
10289  Beauty      August 6, 2018               2.5.1        4.0.3 and up
Group Name : BOOKS_AND_REFERENCE
Group Info :
                                       App             Category  Rating  \
139                  Wattpad 📖 Free Books  BOOKS_AND_REFERENCE     4.6
140      E-Book Read - Read Book for free  BOOKS_AND_REFERENCE     4.5
141    Download free book with green book  BOOKS_AND_REFERENCE     4.6
142                             Wikipedia  BOOKS_AND_REFERENCE     4.4
143                         Amazon Kindle  BOOKS_AND_REFERENCE     4.2
...                                   ...                  ...     ...
10815           Golden Dictionary (FR-AR)  BOOKS_AND_REFERENCE     4.2
10819                           Fanfic-FR  BOOKS_AND_REFERENCE     3.3
10829      Bulgarian French Dictionary Fr  BOOKS_AND_REFERENCE     4.6
10833                         Chemin (fr)  BOOKS_AND_REFERENCE     4.8
10839       The SCP Foundation DB fr nn5n  BOOKS_AND_REFERENCE     4.5

       Reviews                Size      Installs  Type Price Content Rating  \
139    2914724  Varies with device  100,000,000+  Free     0           Teen
140       1857                4.9M       50,000+  Free     0       Everyone
141       4478                9.5M      100,000+  Free     0   Everyone 10+
142     577550  Varies with device   10,000,000+  Free     0       Everyone
143     814080  Varies with device  100,000,000+  Free     0           Teen
...        ...                 ...           ...   ...   ...            ...
10815     5775                4.9M      500,000+  Free     0       Everyone
10819       52                3.6M        5,000+  Free     0           Teen
10829      603                7.4M       10,000+  Free     0       Everyone
10833       44                619k        1,000+  Free     0       Everyone
10839      114  Varies with device        1,000+  Free     0     Mature 17+

                  Genres      Last Updated         Current Ver  \
139    Books & Reference    August 1, 2018  Varies with device

In [55]:
# 9 Find Whic Category Higest getting Average Ratting
# 2  Get the Rating of Every Category
for ra in df.groupby('Category')["Rating"]:
    print(ra)

('1.9', 10472    19.0
Name: Rating, dtype: float64)
('ART_AND_DESIGN', 0       4.1
1       3.9
2       4.7
3       4.5
4       4.3
       ...
7174    NaN
8679    4.2
8712    4.3
8871    NaN
8888    5.0
Name: Rating, Length: 65, dtype: float64)
('AUTO_AND_VEHICLES', 49       4.2
50       4.0
51       3.8
52       4.6
53       3.9
        ...
10137    2.1
10345    3.9
10486    4.6
10764    NaN
10811    NaN
Name: Rating, Length: 85, dtype: float64)
('BEAUTY', 98       4.7
99       4.9
100      4.7
101      3.9
102      3.9
103      4.2
104      4.6
105      4.3
106      4.7
107      4.7
108      4.8
109      4.2
110      4.3
111      4.5
112      4.1
113      NaN
114      4.2
115      4.5
116      4.4
117      4.0
118      4.1
119      4.1
120      4.4
121      4.6
122      4.5
123      NaN
124      3.9
125      4.4
126      NaN
127      4.6
128      3.8
129      NaN
130      NaN
131      4.0
132      4.3
133      4.5
134      NaN
135      4.1
136      3.7
137      4.7
138      4.2
5192     3.1
5998     NaN
6222     4.0
6318     NaN
6506     4.0
6828     NaN
7021     4.5
7460     NaN
8505     NaN
9205     4.0
10022    4.7
10289    3.9
Name: Rating, dtype: float64)
('BOOKS_AND_REFERENCE', 139      4.6
140      4.5
141      4.6
142      4.4
143      4.2
        ...
10815    4.2
10819    3.3
10829    4.6
10833    4.8
10839    4.5
Name: Rating, Length: 231, dtype: float64)
('BUSINESS', 187      4.1
188      4.3
189      4.4
190      4.3
191      4.3
        ...
10772    NaN
10810    4.8
10813    NaN
10816    NaN
10835    NaN
Name: Rating, Length: 460, dtype: float64)
('COMICS', 297      4.5
298      4.6
299      4.7
300      4.7
301      4.8
302      3.9
303      4.1
304      4.4
305      4.6
306      4.5
307      4.7
308      4.4
309      4.5
310      3.9
311      3.2
312      3.2
313      4.1
314      4.5
315      4.2
316      4.2
317      3.7
318      4.5
319      4.6
320      4.5
321      NaN
322      4.7
323      4.4
324      3.5
325      3.3
326      4.5
327      4.4
328      4.2
329      5.0
330      4.4
331      4.7
332      4.4
333      4.4
334      4.6
4506     4.4
4724     4.5
4959     3.7
5041     2.8
5905     3.3
5936     4.1
6009     3.3
6015     3.9
6072     4.0
6407     4.8
6408     3.0
6411     3.2
6414     3.5
6420     4.4
6424     3.8
6705     4.3
7992     3.8
8246     4.2
8257     4.1
8260     5.0
8278     NaN
10828    3.4
Name: Rating, dtype: float64)
('COMMUNICATION', 335      4.0
336      4.4
337      4.3
338      4.3
339      4.4
        ...
10720    4.4
10734    NaN
10739    3.6
10748    NaN
10790    4.1
Name: Rating, Length: 387, dtype: float64)
('DATING', 476      4.2
477      2.6
478      NaN
479      NaN
480      NaN
        ...
7077     4.0
7303     3.5
10045    4.1
10168    3.7
10715    3.0
Name: Rating, Length: 234, dtype: float64)
('EDUCATION', 699    4.7
700    4.6
701    4.7
702    4.6
703    4.7
      ...
850    4.1
851    4.9
852    4.7
853    4.7
854    4.7
Name: Rating, Length: 156, dtype: float64)
('ENTERTAINMENT', 855     4.4
856     4.0
857     4.2
858     4.3
859     4.5
       ...
999     4.2
1000    4.3
1001    4.6
1002    4.3
1003    4.5
Name: Rating, Length: 149, dtype: float64)
('EVENTS', 1004     4.0
1005     4.0
1006     4.5
1007     4.5
1008     4.0
        ...
9659     5.0
9699     NaN
10105    NaN
10605    NaN
10767    4.8
Name: Rating, Length: 64, dtype: float64)
('FAMILY', 2014     4.5
2015     4.4
2016     4.5
2017     4.4
2018     4.4
        ...
10821    NaN
10827    4.2
10834    4.0
10836    4.5
10837    5.0
Name: Rating, Length: 1972, dtype: float64)
('FINANCE', 1048     4.4
1049     4.4
1050     3.6
1051     3.7
1052     3.8
        ...
10718    3.9
10744    NaN
10745    NaN
10752    3.6
10818    NaN
Name: Rating, Length: 366, dtype: float64)
('FOOD_AND_DRINK', 1176     3.6
1177     NaN
1178     4.1
1179     4.6
1180     NaN
        ...
9487     4.4
9540     4.0
9819     4.6
9834     NaN
10347    NaN
Name: Rating, Length: 127, dtype: float64)
('GAME', 1653     4.5
1654     4.5
1655     4.4
1656     4.7
1657     4.5
        ...
10791    4.0
10792    4.2
10793    4.4
10803    4.3
10804    4.2
Name: Rating, Length: 1144, dtype: float64)
('HEALTH_AND_FITNESS', 1256     4.8
1257     4.0
1258     4.9
1259     4.8
1260     4.9
        ...
10362    4.5
10402    NaN
10600    3.5
10630    3.2
10760    4.4
Name: Rating, Length: 341, dtype: float64)
('HOUSE_AND_HOME', 1446     4.5
1447     4.8
1448     4.2
1449     4.5
1450     4.1
        ...
9962     NaN
9982     4.3
9984     3.9
10119    NaN
10348    NaN
Name: Rating, Length: 88, dtype: float64)
('LIBRARIES_AND_DEMO', 1514     3.9
1515     4.4
1516     4.6
1517     NaN
1518     4.1
        ...
8203     4.5
9790     4.2
9893     NaN
10290    4.1
10729    4.3
Name: Rating, Length: 85, dtype: float64)
('LIFESTYLE', 1562     4.1
1563     4.1
1564     4.3
1565     4.0
1566     4.6
        ...
10773    NaN
10797    4.6
10805    4.3
10808    NaN
10840    4.5
Name: Rating, Length: 382, dtype: float64)
('MAPS_AND_NAVIGATION', 3820     4.6
3821     4.2
3822     4.1
3823     4.4
3824     4.4
        ...
10638    4.2
10725    3.6
10737    4.0
10755    4.3
10831    NaN
Name: Rating, Length: 137, dtype: float64)
('MEDICAL', 2243     4.2
2244     4.4
2245     4.6
2246     4.5
2247     4.8
        ...
10730    4.5
10768    3.8
10806    NaN
10824    NaN
10838    NaN
Name: Rating, Length: 463, dtype: float64)
('NEWS_AND_MAGAZINES', 3715     4.5
3716     4.4
3717     4.3
3718     4.5
3719     4.3
        ...
10646    4.6
10680    4.4
10762    NaN
10774    NaN
10830    3.8
Name: Rating, Length: 283, dtype: float64)
('PARENTING', 3575    4.5
3576    3.9
3577    NaN
3578    3.8
3579    NaN
3580    NaN
3581    4.6
3582    4.7
3583    NaN
3584    4.0
3585    NaN
3586    4.7
3587    4.1
3588    3.7
3589    NaN
3590    4.1
3591    3.7
3592    4.6
3593    4.4
3594    4.6
3595    4.1
3596    4.4
3597    4.7
3598    4.4
3599    NaN
3600    4.8
3601    4.0
3602    4.9
3603    NaN
3604    4.8
3605    4.4
3606    4.7
3607    4.2
3608    4.6
3609    4.6
3610    4.5
3611    4.6
3612    4.1
3613    3.8
3614    4.8
3615    4.8
3616    NaN
3617    4.5
3618    4.0
3619    4.4
3620    4.7
3621    NaN
3622    3.9
3623    4.4
3624    4.4
3625    4.5
4608    3.1
5920    4.2
5973    4.7
6486    4.3
7229    4.7
7631    3.5
7658    2.0
8335    5.0
9311    4.1
Name: Rating, dtype: float64)
('PERSONALIZATION', 3352     4.6
3353     4.4
3354     4.6
3355     4.6
3356     4.5
        ...
10710    3.8
10722    4.0
10733    3.5
10747    3.5
10788    NaN
Name: Rating, Length: 392, dtype: float64)
('PHOTOGRAPHY', 2801     4.1
2802     4.6
2803     4.8
2804     4.0
2805     4.7
        ...
10666    4.6
10707    4.5
10716    4.2
10726    4.4
10740    4.3
Name: Rating, Length: 335, dtype: float64)
('PRODUCTIVITY', 3450     4.5
3451     4.7
3452     4.3
3453     4.4
3454     4.4
        ...
10606    NaN
10622    NaN
10681    4.6
10771    3.9
10822    NaN
Name: Rating, Length: 424, dtype: float64)
('SHOPPING', 2654     4.0
2655     4.5
2656     4.6
2657     4.3
2658     4.2
        ...
10106    NaN
10276    4.1
10642    3.9
10712    4.4
10753    4.5
Name: Rating, Length: 260, dtype: float64)
('SOCIAL', 2544     4.1
2545     4.5
2546     4.3
2547     4.4
2548     4.4
        ...
10714    4.4
10765    3.4
10799    4.7
10825    NaN
10826    4.0
Name: Rating, Length: 295, dtype: float64)
('SPORTS', 2959     4.2
2960     4.3
2961     4.4
2962     4.2
2963     4.1
        ...
10604    4.7
10645    3.9
10683    4.2
10723    4.3
10775    NaN
Name: Rating, Length: 384, dtype: float64)
('TOOLS', 3233     4.1
3234     4.4
3235     4.4
3236     4.2
3237     4.2
        ...
10795    4.2
10796    4.7
10800    4.1
10807    NaN
10817    4.0
Name: Rating, Length: 843, dtype: float64)
('TRAVEL_AND_LOCAL', 3102     4.1
3103     4.2
3104     4.4
3105     4.4
3106     4.1
        ...
10608    NaN
10621    5.0
10631    NaN
10633    3.8
10634    4.6
Name: Rating, Length: 258, dtype: float64)
('VIDEO_PLAYERS', 3665     4.3
3666     4.3
3667     4.2
3668     4.3
3669     3.6
        ...
10237    4.2
10318    4.4
10519    NaN
10647    3.9
10823    NaN
Name: Rating, Length: 175, dtype: float64)
('WEATHER', 3626     4.4
3627     4.8
3628     4.4
3629     4.8
3630     4.5
        ...
10612    NaN
10625    NaN
10627    NaN
10713    4.4
10832    3.8
Name: Rating, Length: 82, dtype: float64)

In [56]:
# 9 Find Whic Category Higest getting Average Ratting
#  3 Find the Mean of Rating of every Category
df.groupby('Category')["Rating"].mean()

Category
1.9                    19.000000
ART_AND_DESIGN          4.358065
AUTO_AND_VEHICLES       4.190411
BEAUTY                  4.278571
BOOKS_AND_REFERENCE     4.346067
BUSINESS                4.121452
COMICS                  4.155172
COMMUNICATION           4.158537
DATING                  3.970769
EDUCATION               4.389032
ENTERTAINMENT           4.126174
EVENTS                  4.435556
FAMILY                  4.192272
FINANCE                 4.131889
FOOD_AND_DRINK          4.166972
GAME                    4.286326
HEALTH_AND_FITNESS      4.277104
HOUSE_AND_HOME          4.197368
LIBRARIES_AND_DEMO      4.178462
LIFESTYLE               4.094904
MAPS_AND_NAVIGATION     4.051613
MEDICAL                 4.189143
NEWS_AND_MAGAZINES      4.132189
PARENTING               4.300000
PERSONALIZATION         4.335987
PHOTOGRAPHY             4.192114
PRODUCTIVITY            4.211396
SHOPPING                4.259664
SOCIAL                  4.255598
SPORTS                  4.223511
TOOLS                   4.047411
TRAVEL_AND_LOCAL        4.109292
VIDEO_PLAYERS           4.063750
WEATHER                 4.244000
Name: Rating, dtype: float64

In [57]:
# 9 Find Whic Category Higest getting Average Ratting
#  4 Find the Higet Average Rating 
df.groupby('Category')["Rating"].mean().sort_values()

Category
DATING                  3.970769
TOOLS                   4.047411
MAPS_AND_NAVIGATION     4.051613
VIDEO_PLAYERS           4.063750
LIFESTYLE               4.094904
TRAVEL_AND_LOCAL        4.109292
BUSINESS                4.121452
ENTERTAINMENT           4.126174
FINANCE                 4.131889
NEWS_AND_MAGAZINES      4.132189
COMICS                  4.155172
COMMUNICATION           4.158537
FOOD_AND_DRINK          4.166972
LIBRARIES_AND_DEMO      4.178462
MEDICAL                 4.189143
AUTO_AND_VEHICLES       4.190411
PHOTOGRAPHY             4.192114
FAMILY                  4.192272
HOUSE_AND_HOME          4.197368
PRODUCTIVITY            4.211396
SPORTS                  4.223511
WEATHER                 4.244000
SOCIAL                  4.255598
SHOPPING                4.259664
HEALTH_AND_FITNESS      4.277104
BEAUTY                  4.278571
GAME                    4.286326
PARENTING               4.300000
PERSONALIZATION         4.335987
BOOKS_AND_REFERENCE     4.346067
ART_AND_DESIGN          4.358065
EDUCATION               4.389032
EVENTS                  4.435556
1.9                    19.000000
Name: Rating, dtype: float64

In [59]:
df.groupby('Category')["Rating"].mean().sort_values(ascending=False)

Category
1.9                    19.000000
EVENTS                  4.435556
EDUCATION               4.389032
ART_AND_DESIGN          4.358065
BOOKS_AND_REFERENCE     4.346067
PERSONALIZATION         4.335987
PARENTING               4.300000
GAME                    4.286326
BEAUTY                  4.278571
HEALTH_AND_FITNESS      4.277104
SHOPPING                4.259664
SOCIAL                  4.255598
WEATHER                 4.244000
SPORTS                  4.223511
PRODUCTIVITY            4.211396
HOUSE_AND_HOME          4.197368
FAMILY                  4.192272
PHOTOGRAPHY             4.192114
AUTO_AND_VEHICLES       4.190411
MEDICAL                 4.189143
LIBRARIES_AND_DEMO      4.178462
FOOD_AND_DRINK          4.166972
COMMUNICATION           4.158537
COMICS                  4.155172
NEWS_AND_MAGAZINES      4.132189
FINANCE                 4.131889
ENTERTAINMENT           4.126174
BUSINESS                4.121452
TRAVEL_AND_LOCAL        4.109292
LIFESTYLE               4.094904
VIDEO_PLAYERS           4.063750
MAPS_AND_NAVIGATION     4.051613
TOOLS                   4.047411
DATING                  3.970769
Name: Rating, dtype: float64

In [61]:
# 10 Find the total number App having 5 Star Rating Apps
# 0 Find Column Name
df.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='object')

In [65]:
# 10 Find the total number App having 5 Star Rating Apps
# 1 Find The Rating Values
df['Rating']

0        4.1
1        3.9
2        4.7
3        4.5
4        4.3
        ...
10836    4.5
10837    5.0
10838    NaN
10839    4.5
10840    4.5
Name: Rating, Length: 10841, dtype: float64

In [69]:
# 10 Find the total number App having 5 Star Rating Apps
# 2 Find The Rating Values is Equale to 5
df['Rating']==5

0        False
1        False
2        False
3        False
4        False
         ...
10836    False
10837     True
10838    False
10839    False
10840    False
Name: Rating, Length: 10841, dtype: bool

In [70]:
# 10 Find the total number App having 5 Star Rating Apps
# 3 Get the app name passing to boolean values to DataFrame
df[df['Rating']==5]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
329,Hojiboy Tojiboyev Life Hacks,COMICS,5.0,15,37M,"1,000+",Free,0,Everyone,Comics,"June 26, 2018",2.0,4.0.3 and up
612,American Girls Mobile Numbers,DATING,5.0,5,4.4M,"1,000+",Free,0,Mature 17+,Dating,"July 17, 2018",3.0,4.0.3 and up
615,Awake Dating,DATING,5.0,2,70M,100+,Free,0,Mature 17+,Dating,"July 24, 2018",2.2.9,4.4 and up
633,Spine- The dating app,DATING,5.0,5,9.3M,500+,Free,0,Teen,Dating,"July 14, 2018",4.0,4.0.3 and up
636,Girls Live Talk - Free Text and Video Chat,DATING,5.0,6,5.0M,100+,Free,0,Mature 17+,Dating,"August 1, 2018",8.2,4.0.3 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10721,Mad Dash Fo' Cash,GAME,5.0,14,16M,100+,Free,0,Everyone,Arcade,"June 19, 2017",2.5a,4.1 and up
10742,GKPB FP Online Church,LIFESTYLE,5.0,32,7.9M,"1,000+",Free,0,Everyone,Lifestyle,"December 31, 2017",0.7.1,4.4 and up
10776,Monster Ride Pro,GAME,5.0,1,24M,10+,Free,0,Everyone,Racing,"March 5, 2018",2.0,2.3 and up
10820,Fr. Daoud Lamei,FAMILY,5.0,22,8.6M,"1,000+",Free,0,Teen,Education,"June 27, 2018",3.8.0,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up

In [71]:
# 10 Find the total number App having 5 Star Rating Apps
# 4 Get Total Number of App names having 5 Star Rating
len(df[df['Rating']==5])

274

In [74]:
# 11 Find The Average Values of Reviews
df["Reviews"].dtype

dtype('O')

In [75]:
# 11 Find The Average Values of Reviews
  # Covert Dtype 
df["Reviews"].astype("float")

ValueError: could not convert string to float: '3.0M'

In [77]:
# 11 Find The Average Values of Reviews
  # Find the App reviews values is 3.0M
df[df["Reviews"]=='3.0M']

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10472,Life Made WI-Fi Touchscreen Photo Frame,1.9,19.0,3.0M,"1,000+",Free,0,Everyone,NaN,"February 11, 2018",1.0.19,4.0 and up,NaN

In [81]:
# 11 Find The Average Values of Reviews
  # Replace the values 3.0M to 3.0
df["Reviews"]=df["Reviews"].replace('3.0M',3.0)
print(df["Reviews"])

0           159
1           967
2         87510
3        215644
4           967
          ...
10836        38
10837         4
10838         3
10839       114
10840    398307
Name: Reviews, Length: 10841, dtype: object

In [84]:
# 11 Find The Average Values of Reviews
  # Covert Dtype (O) to float 
df["Reviews"]=df["Reviews"].astype("float")

In [85]:
df["Reviews"].dtype

dtype('float64')

In [86]:
# 11 Find The Average Values of Reviews
# Now to get Average reviews 
df["Reviews"].mean()

np.float64(444111.9265750392)

In [93]:
# 12 Find Total Niumber of free app and Paid app
df["Type"]

0        Free
1        Free
2        Free
3        Free
4        Free
         ...
10836    Free
10837    Free
10838    Free
10839    Free
10840    Free
Name: Type, Length: 10841, dtype: object

In [94]:
# 12 Find Total Niumber of free app and Paid app
# free
df[df["Type"]=='Free']

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [95]:
# 12 Find Total Niumber of free app and Paid app
# Paid
df[df["Type"]=='Paid']

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
234,TurboScan: scan documents and receipts in PDF,BUSINESS,4.7,11442,6.8M,"100,000+",Paid,$4.99,Everyone,Business,"March 25, 2018",1.5.2,4.0 and up
235,Tiny Scanner Pro: PDF Doc Scan,BUSINESS,4.8,10295,39M,"100,000+",Paid,$4.99,Everyone,Business,"April 11, 2017",3.4.6,3.0 and up
290,TurboScan: scan documents and receipts in PDF,BUSINESS,4.7,11442,6.8M,"100,000+",Paid,$4.99,Everyone,Business,"March 25, 2018",1.5.2,4.0 and up
291,Tiny Scanner Pro: PDF Doc Scan,BUSINESS,4.8,10295,39M,"100,000+",Paid,$4.99,Everyone,Business,"April 11, 2017",3.4.6,3.0 and up
427,Puffin Browser Pro,COMMUNICATION,4.0,18247,Varies with device,"100,000+",Paid,$3.99,Everyone,Communication,"July 5, 2018",7.5.3.20547,4.1 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10735,FP VoiceBot,FAMILY,NaN,17,157k,100+,Paid,$0.99,Mature 17+,Entertainment,"November 25, 2015",1.2,2.1 and up
10760,Fast Tract Diet,HEALTH_AND_FITNESS,4.4,35,2.4M,"1,000+",Paid,$7.99,Everyone,Health & Fitness,"August 8, 2018",1.9.3,4.2 and up
10782,Trine 2: Complete Story,GAME,3.8,252,11M,"10,000+",Paid,$16.99,Teen,Action,"February 27, 2015",2.22,5.0 and up
10785,"sugar, sugar",FAMILY,4.2,1405,9.5M,"10,000+",Paid,$1.20,Everyone,Puzzle,"June 5, 2018",2.7,2.3 and up
10798,Word Search Tab 1 FR,FAMILY,NaN,0,1020k,50+,Paid,$1.04,Everyone,Puzzle,"February 6, 2012",1.1,3.0 and up

In [100]:
# 12 Find Total Niumber of free app and Paid app
# free
df["Type"].value_counts()

Type
Free    10039
Paid      800
0           1
Name: count, dtype: int64

In [101]:
# 13 Find Which App has Maximum Reviews
df["Reviews"].max()

'9992'

In [102]:
# 13 Find Which App has Maximum Reviews
# Gets the complete app details in Bollean
df["Reviews"].max()==df["Reviews"]

0        False
1        False
2        False
3        False
4        False
         ...
10836    False
10837    False
10838    False
10839    False
10840    False
Name: Reviews, Length: 10841, dtype: bool

In [103]:
# 13 Find Which App has Maximum Reviews
# Gets the complete app details
df[df["Reviews"].max()==df["Reviews"]]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
2989,GollerCepte Live Score,SPORTS,4.2,9992,31M,"1,000,000+",Free,0,Everyone,Sports,"May 23, 2018",6.5,4.1 and up

In [104]:
# 13 Find Which App has Maximum Reviews
# Gets app name
df[df["Reviews"].max()==df["Reviews"]]["App"]

2989    GollerCepte Live Score
Name: App, dtype: object

In [112]:
# 14 Find the top 5 app name having higest Review
df["Reviews"].sort_values().tail().index

Index([3049, 2723, 2705, 4970, 2989], dtype='int64')

In [110]:
# 14 Find the top 5 app name having higest Review
df.iloc[df["Reviews"].sort_values().tail().index]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
3049,US Open Tennis Championships 2018,SPORTS,4.0,9971,33M,"1,000,000+",Free,0,Everyone,Sports,"June 5, 2018",7.1,5.0 and up
2723,SnipSnap Coupon App,SHOPPING,4.2,9975,18M,"1,000,000+",Free,0,Everyone,Shopping,"January 22, 2018",1.4,4.3 and up
2705,SnipSnap Coupon App,SHOPPING,4.2,9975,18M,"1,000,000+",Free,0,Everyone,Shopping,"January 22, 2018",1.4,4.3 and up
4970,Ad Block REMOVER - NEED ROOT,TOOLS,3.3,999,91k,"100,000+",Free,0,Everyone,Tools,"December 17, 2013",3.2,2.2 and up
2989,GollerCepte Live Score,SPORTS,4.2,9992,31M,"1,000,000+",Free,0,Everyone,Sports,"May 23, 2018",6.5,4.1 and up

In [111]:
# 14 Find the top 5 app name having higest Review
df.iloc[df["Reviews"].sort_values().tail().index]["App"]

3049    US Open Tennis Championships 2018
2723                  SnipSnap Coupon App
2705                  SnipSnap Coupon App
4970         Ad Block REMOVER - NEED ROOT
2989               GollerCepte Live Score
Name: App, dtype: object

In [118]:
# 15 Find the Average Rating of Free and Paid Apps
df["Type"]

0        Free
1        Free
2        Free
3        Free
4        Free
         ...
10836    Free
10837    Free
10838    Free
10839    Free
10840    Free
Name: Type, Length: 10841, dtype: object

In [129]:
for gp,gpinfo in df.groupby("Type")["Rating"]:
    if(gp=="Free" or gp=="Paid"):
        print("Group  Name :",gp)
        print("Group Info :",gpinfo.mean())

Group  Name : Free
Group Info : 4.186202546163551
Group  Name : Paid
Group Info : 4.26661514683153

In [138]:
# 16 Find Top 5 Apps Having Maximum Installs
df["Installs"]

0            10,000+
1           500,000+
2         5,000,000+
3        50,000,000+
4           100,000+
            ...
10836         5,000+
10837           100+
10838         1,000+
10839         1,000+
10840    10,000,000+
Name: Installs, Length: 10841, dtype: object

In [162]:
# 16 Find Top 5 Apps Having Maximum Installs
# Convert Dtype 
# df["Installs"].astype("int")
df["Installs_1"]=df["Installs"].str.replace(",","")
df["Installs_1"]=df["Installs_1"].str.replace("+","")

In [163]:
df["Installs_1"]

0           10000
1          500000
2         5000000
3        50000000
4          100000
           ...
10836        5000
10837         100
10838        1000
10839        1000
10840    10000000
Name: Installs_1, Length: 10841, dtype: object

In [168]:
df["Installs_1"].dtype

dtype('O')

In [170]:
df[df["Installs_1"]=="Free"]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Installs_1
10472,Life Made WI-Fi Touchscreen Photo Frame,1.9,19.0,3.0M,"1,000+",Free,0,Everyone,NaN,"February 11, 2018",1.0.19,4.0 and up,NaN,Free

In [171]:
df["Installs_1"]=df["Installs_1"].str.replace("Free","0")

In [172]:
df["Installs_1"]

0           10000
1          500000
2         5000000
3        50000000
4          100000
           ...
10836        5000
10837         100
10838        1000
10839        1000
10840    10000000
Name: Installs_1, Length: 10841, dtype: object

In [175]:
df["Installs_1"]=df["Installs_1"].astype("int")
print(df["Installs_1"])

0           10000
1          500000
2         5000000
3        50000000
4          100000
           ...
10836        5000
10837         100
10838        1000
10839        1000
10840    10000000
Name: Installs_1, Length: 10841, dtype: int64

In [180]:
df["Installs_1"].sort_values().tail()

335     1000000000
336     1000000000
451     1000000000
1917    1000000000
152     1000000000
Name: Installs_1, dtype: int64

In [182]:
df.iloc[df["Installs_1"].sort_values().tail().index]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Installs_1
335,Messenger – Text and Video Chat for Free,COMMUNICATION,4.0,56642847,Varies with device,"1,000,000,000+",Free,0,Everyone,Communication,"August 1, 2018",Varies with device,Varies with device,1000000000
336,WhatsApp Messenger,COMMUNICATION,4.4,69119316,Varies with device,"1,000,000,000+",Free,0,Everyone,Communication,"August 3, 2018",Varies with device,Varies with device,1000000000
451,Gmail,COMMUNICATION,4.3,4604483,Varies with device,"1,000,000,000+",Free,0,Everyone,Communication,"August 2, 2018",Varies with device,Varies with device,1000000000
1917,Subway Surfers,GAME,4.5,27725352,76M,"1,000,000,000+",Free,0,Everyone 10+,Arcade,"July 12, 2018",1.90.0,4.1 and up,1000000000
152,Google Play Books,BOOKS_AND_REFERENCE,3.9,1433233,Varies with device,"1,000,000,000+",Free,0,Teen,Books & Reference,"August 3, 2018",Varies with device,Varies with device,1000000000

In [186]:
df.iloc[df["Installs_1"].sort_values().tail().index][["App","Installs"]]

                                           App        Installs
335   Messenger – Text and Video Chat for Free  1,000,000,000+
336                         WhatsApp Messenger  1,000,000,000+
451                                      Gmail  1,000,000,000+
1917                            Subway Surfers  1,000,000,000+
152                          Google Play Books  1,000,000,000+